import type { Dialog } from "./content";

export const DIALOGS: Dialog[] = [
  {
    id: "healthcare-admission",
    title: "Patient Admission",
    titleEs: "Admisión de Paciente",
    industry: "healthcare",
    level: "beginner",
    vocabulary: [
      {
        word: "insurance",
        pronunciation: "/ɪnˈʃʊərəns/",
        definitionEn: "Coverage that pays for medical costs",
        definitionEs: "Seguro médico que cubre gastos",
        example: "Do you have health insurance?",
      },
      {
        word: "symptoms",
        pronunciation: "/ˈsɪmptəmz/",
        definitionEn: "Physical signs of illness",
        definitionEs: "Señales físicas de enfermedad",
        example: "What symptoms are you experiencing?",
      },
      {
        word: "appointment",
        pronunciation: "/əˈpɔɪntmənt/",
        definitionEn: "A scheduled meeting or visit",
        definitionEs: "Una cita programada",
        example: "I have an appointment at 3 PM.",
      },
    ],
    culturalNote:
      "In US healthcare settings, always confirm insurance information and ask about allergies before any procedure.",
    culturalNoteEs:
      "En centros de salud en EE.UU., siempre confirme el seguro médico y pregunte sobre alergias antes de cualquier procedimiento.",
    lines: [
      {
        speaker: "Receptionist",
        role: "Medical Receptionist",
        roleEs: "Recepcionista Médica",
        text: "Good morning! Welcome to Riverside Medical Center. How can I help you today?",
        textEs: "¡Buenos días! Bienvenido al Centro Médico Riverside. ¿En qué le puedo ayudar hoy?",
        tip: "Always greet with a warm, professional tone. Use 'How can I help you?' not 'What do you want?'",
        tipEs: "Siempre salude con tono cálido y profesional. Use 'How can I help you?' en vez de 'What do you want?'",
      },
      {
        speaker: "Patient",
        role: "Patient",
        roleEs: "Paciente",
        text: "Good morning. I have an appointment with Dr. Johnson at 10 o'clock.",
        textEs: "Buenos días. Tengo una cita con la Dra. Johnson a las 10.",
        tip: "State your appointment time clearly. Say 'at 10 o'clock' or 'at 10 AM'.",
        tipEs: "Diga la hora claramente. Diga 'at 10 o'clock' o 'at 10 AM'.",
      },
      {
        speaker: "Receptionist",
        role: "Medical Receptionist",
        roleEs: "Recepcionista Médica",
        text: "Perfect. Can I have your full name and date of birth, please?",
        textEs: "Perfecto. ¿Me puede dar su nombre completo y fecha de nacimiento, por favor?",
        tip: "Use 'Can I have...' or 'May I have...' to request information politely.",
        tipEs: "Use 'Can I have...' o 'May I have...' para pedir información con cortesía.",
      },
      {
        speaker: "Patient",
        role: "Patient",
        roleEs: "Paciente",
        text: "Yes, my name is Carlos Rivera, and my date of birth is March 15, 1985.",
        textEs: "Sí, mi nombre es Carlos Rivera, y mi fecha de nacimiento es el 15 de marzo de 1985.",
        tip: "In the US, dates are said as: Month + Day + Year. March fifteenth, nineteen eighty-five.",
        tipEs: "En EE.UU. las fechas se dicen: Mes + Día + Año. March fifteenth, nineteen eighty-five.",
      },
      {
        speaker: "Receptionist",
        role: "Medical Receptionist",
        roleEs: "Recepcionista Médica",
        text: "Thank you, Mr. Rivera. Do you have your insurance card with you today?",
        textEs: "Gracias, Sr. Rivera. ¿Tiene su tarjeta de seguro médico hoy?",
        tip: "Always bring your insurance card to medical appointments. It's essential.",
        tipEs: "Siempre traiga su tarjeta de seguro a las citas médicas. Es esencial.",
      },
      {
        speaker: "Patient",
        role: "Patient",
        roleEs: "Paciente",
        text: "Yes, here it is. I also have a new address since my last visit.",
        textEs: "Sí, aquí está. También tengo una nueva dirección desde mi última visita.",
        tip: "Say 'Here it is' when handing something. 'Since my last visit' shows good professional vocabulary.",
        tipEs: "Diga 'Here it is' al entregar algo. 'Since my last visit' muestra buen vocabulario profesional.",
      },
      {
        speaker: "Receptionist",
        role: "Medical Receptionist",
        roleEs: "Recepcionista Médica",
        text: "No problem. I'll update that for you. Please have a seat in the waiting area. The doctor will be with you shortly.",
        textEs: "Sin problema. Lo actualizaré. Por favor tome asiento en la sala de espera. La doctora le atenderá pronto.",
        tip: "'Shortly' means 'in a little while'. 'Have a seat' is the polite way to say 'sit down'.",
        tipEs: "'Shortly' significa 'en poco tiempo'. 'Have a seat' es la forma cortés de decir 'siéntese'.",
      },
    ],
  },
  {
    id: "construction-safety",
    title: "Job Site Safety Briefing",
    titleEs: "Briefing de Seguridad en Obra",
    industry: "construction",
    level: "intermediate",
    vocabulary: [
      {
        word: "PPE",
        pronunciation: "/piː piː iː/",
        definitionEn: "Personal Protective Equipment — safety gear required on site",
        definitionEs: "Equipo de Protección Personal — equipo de seguridad requerido en obra",
        example: "All workers must wear PPE at all times.",
      },
      {
        word: "hazard",
        pronunciation: "/ˈhæzərd/",
        definitionEn: "A danger or risk in the workplace",
        definitionEs: "Un peligro o riesgo en el lugar de trabajo",
        example: "Report any hazards to your supervisor immediately.",
      },
      {
        word: "foreman",
        pronunciation: "/ˈfɔːrmən/",
        definitionEn: "The supervisor in charge of a construction crew",
        definitionEs: "El capataz a cargo de una cuadrilla de construcción",
        example: "Check with the foreman before starting any new task.",
      },
    ],
    culturalNote:
      "OSHA regulations require safety briefings on US job sites. Always ask questions if you're unsure — it shows responsibility, not weakness.",
    culturalNoteEs:
      "Las regulaciones OSHA requieren briefings de seguridad en obras en EE.UU. Siempre haga preguntas si no está seguro — muestra responsabilidad, no debilidad.",
    lines: [
      {
        speaker: "Foreman",
        role: "Site Foreman",
        roleEs: "Capataz de Obra",
        text: "Alright everyone, listen up. Before we start today, I need to go over the safety protocols for this site.",
        textEs: "Bien todos, pongan atención. Antes de empezar hoy, necesito repasar los protocolos de seguridad de esta obra.",
        tip: "'Listen up' is informal but common on job sites. It means 'pay attention now'.",
        tipEs: "'Listen up' es informal pero común en obras. Significa 'pongan atención ahora'.",
      },
      {
        speaker: "Worker",
        role: "Construction Worker",
        roleEs: "Trabajador de Construcción",
        text: "Good morning. Are there any changes from yesterday's briefing?",
        textEs: "Buenos días. ¿Hay cambios desde el briefing de ayer?",
        tip: "Asking about changes shows you're engaged and professional. Great habit on US job sites.",
        tipEs: "Preguntar sobre cambios muestra que está involucrado y es profesional. Gran hábito en obras en EE.UU.",
      },
      {
        speaker: "Foreman",
        role: "Site Foreman",
        roleEs: "Capataz de Obra",
        text: "Yes. We're starting work on the third floor today, so all workers must wear hard hats and harnesses at all times. No exceptions.",
        textEs: "Sí. Hoy empezamos trabajo en el tercer piso, así que todos los trabajadores deben usar casco y arnés en todo momento. Sin excepciones.",
        tip: "'No exceptions' is a firm professional phrase meaning the rule applies to everyone.",
        tipEs: "'No exceptions' es una frase profesional firme que significa que la regla aplica para todos.",
      },
      {
        speaker: "Worker",
        role: "Construction Worker",
        roleEs: "Trabajador de Construcción",
        text: "Understood. Should we also use the safety lines when near the edge?",
        textEs: "Entendido. ¿También debemos usar las líneas de seguridad cerca del borde?",
        tip: "'Understood' is a strong, professional way to confirm you received instructions.",
        tipEs: "'Understood' es una forma fuerte y profesional de confirmar que recibió las instrucciones.",
      },
      {
        speaker: "Foreman",
        role: "Site Foreman",
        roleEs: "Capataz de Obra",
        text: "Absolutely. If you're within six feet of any edge, the safety line is required. If you notice any hazards, report them to me immediately.",
        textEs: "Absolutamente. Si está a menos de seis pies de cualquier borde, la línea de seguridad es obligatoria. Si nota algún peligro, repórtelo a mí de inmediato.",
        tip: "In the US, measurements are in feet and inches, not meters. 6 feet ≈ 1.8 meters.",
        tipEs: "En EE.UU., las medidas son en pies y pulgadas, no metros. 6 feet ≈ 1.8 metros.",
      },
    ],
  },
  {
    id: "restaurant-order",
    title: "Taking a Customer Order",
    titleEs: "Tomar el Pedido de un Cliente",
    industry: "restaurant",
    level: "beginner",
    vocabulary: [
      {
        word: "specials",
        pronunciation: "/ˈspɛʃəlz/",
        definitionEn: "Daily featured dishes not on the regular menu",
        definitionEs: "Platillos especiales del día que no están en el menú regular",
        example: "Our specials today are the grilled salmon and the pasta primavera.",
      },
      {
        word: "to go",
        pronunciation: "/tʊ ɡoʊ/",
        definitionEn: "Food packaged to take away from the restaurant",
        definitionEs: "Comida empacada para llevar del restaurante",
        example: "Is that for here or to go?",
      },
      {
        word: "modify",
        pronunciation: "/ˈmɒdɪfaɪ/",
        definitionEn: "To change or adjust an order",
        definitionEs: "Cambiar o ajustar un pedido",
        example: "Can I modify my order to remove the onions?",
      },
    ],
    culturalNote:
      "In the US, it's standard to ask about allergies and dietary restrictions. Tipping 15–20% is expected.",
    culturalNoteEs:
      "En EE.UU., es estándar preguntar sobre alergias y restricciones dietéticas. Se espera dar propina del 15–20%.",
    lines: [
      {
        speaker: "Server",
        role: "Restaurant Server",
        roleEs: "Mesero/a",
        text: "Hi there! My name is Maria, and I'll be your server today. Can I start you off with something to drink?",
        textEs: "¡Hola! Me llamo María y seré su mesera hoy. ¿Puedo empezar con algo de tomar?",
        tip: "Introduce yourself by name — this is standard in US restaurants. 'Start you off' means 'begin with'.",
        tipEs: "Preséntese con su nombre — es estándar en restaurantes de EE.UU. 'Start you off' significa 'empezar con'.",
      },
      {
        speaker: "Customer",
        role: "Customer",
        roleEs: "Cliente",
        text: "Yes, I'd like a water and a coffee, please.",
        textEs: "Sí, quisiera agua y café, por favor.",
        tip: "'I'd like' is more polite than 'I want'. Always use it when ordering.",
        tipEs: "'I'd like' es más cortés que 'I want'. Úselo siempre al pedir.",
      },
      {
        speaker: "Server",
        role: "Restaurant Server",
        roleEs: "Mesero/a",
        text: "Of course. Are you ready to order, or do you need a few more minutes?",
        textEs: "Por supuesto. ¿Están listos para ordenar o necesitan unos minutos más?",
        tip: "This phrase gives customers control. In US culture, rushing customers is considered rude.",
        tipEs: "Esta frase le da control al cliente. En la cultura de EE.UU., apresurar a los clientes se considera grosero.",
      },
      {
        speaker: "Customer",
        role: "Customer",
        roleEs: "Cliente",
        text: "We're ready. I'll have the grilled chicken sandwich, but can I get that without the mayo?",
        textEs: "Estamos listos. Quiero el sándwich de pollo a la parrilla, pero ¿me lo puede traer sin mayonesa?",
        tip: "'Can I get that without...' is the natural way to modify your order in the US.",
        tipEs: "'Can I get that without...' es la forma natural de modificar su pedido en EE.UU.",
      },
      {
        speaker: "Server",
        role: "Restaurant Server",
        roleEs: "Mesero/a",
        text: "Absolutely, no problem. And do you have any allergies I should let the kitchen know about?",
        textEs: "Por supuesto, sin problema. ¿Tiene alguna alergia que deba informar a la cocina?",
        tip: "Asking about allergies is professional and shows care. It's required in many US establishments.",
        tipEs: "Preguntar sobre alergias es profesional y muestra cuidado. Es requerido en muchos establecimientos de EE.UU.",
      },
    ],
  },
  {
    id: "office-meeting",
    title: "Running a Team Meeting",
    titleEs: "Dirigir una Reunión de Equipo",
    industry: "office",
    level: "intermediate",
    vocabulary: [
      {
        word: "agenda",
        pronunciation: "/əˈdʒɛndə/",
        definitionEn: "A list of topics to be discussed in a meeting",
        definitionEs: "Una lista de temas a discutir en una reunión",
        example: "Let me share the agenda for today's meeting.",
      },
      {
        word: "action items",
        pronunciation: "/ˈækʃən ˈaɪtəmz/",
        definitionEn: "Tasks assigned during a meeting that need to be completed",
        definitionEs: "Tareas asignadas durante una reunión que deben completarse",
        example: "Let's review the action items from last week.",
      },
      {
        word: "follow up",
        pronunciation: "/ˈfɒloʊ ʌp/",
        definitionEn: "To check on progress or continue a previous discussion",
        definitionEs: "Verificar el progreso o continuar una discusión anterior",
        example: "I'll follow up with the client by Friday.",
      },
    ],
    culturalNote:
      "In US offices, meetings typically start on time. It's professional to send an agenda beforehand and end with clear action items.",
    culturalNoteEs:
      "En oficinas de EE.UU., las reuniones generalmente empiezan a tiempo. Es profesional enviar una agenda de antemano y terminar con tareas claras.",
    lines: [
      {
        speaker: "Manager",
        role: "Team Manager",
        roleEs: "Gerente de Equipo",
        text: "Good morning everyone. Let's get started. I've shared the agenda — today we'll cover the Q3 results, upcoming deadlines, and team announcements.",
        textEs: "Buenos días a todos. Empecemos. Compartí la agenda — hoy cubriremos los resultados del Q3, las fechas límite próximas y los anuncios del equipo.",
        tip: "'Let's get started' signals the meeting is beginning. Much more direct than in Latin American cultures.",
        tipEs: "'Let's get started' indica que la reunión comienza. Mucho más directo que en culturas latinoamericanas.",
      },
      {
        speaker: "Employee",
        role: "Team Member",
        roleEs: "Miembro del Equipo",
        text: "Before we begin, can I add one quick item to the agenda? I have a brief update on the Henderson account.",
        textEs: "Antes de empezar, ¿puedo agregar un punto rápido a la agenda? Tengo una breve actualización sobre la cuenta Henderson.",
        tip: "Always ask permission before adding to the agenda. This shows respect for everyone's time.",
        tipEs: "Siempre pida permiso antes de agregar a la agenda. Esto muestra respeto por el tiempo de todos.",
      },
      {
        speaker: "Manager",
        role: "Team Manager",
        roleEs: "Gerente de Equipo",
        text: "Sure, we can add that at the end. Let's move forward with the Q3 results. Sales hit our target — great work, team.",
        textEs: "Claro, podemos agregarlo al final. Avancemos con los resultados del Q3. Las ventas alcanzaron nuestro objetivo — buen trabajo, equipo.",
        tip: "'Hit our target' is a common business idiom meaning 'achieved our goal'.",
        tipEs: "'Hit our target' es un modismo común en negocios que significa 'logramos nuestra meta'.",
      },
      {
        speaker: "Employee",
        role: "Team Member",
        roleEs: "Miembro del Equipo",
        text: "That's great news. Are there any action items from last quarter that we still need to address?",
        textEs: "Esas son buenas noticias. ¿Hay alguna tarea pendiente del trimestre pasado que aún necesitemos atender?",
        tip: "'Action items' is essential business vocabulary. Always use it in meetings — it sounds highly professional.",
        tipEs: "'Action items' es vocabulario esencial en negocios. Úselo siempre en reuniones — suena muy profesional.",
      },
    ],
  },
  {
    id: "retail-return",
    title: "Processing a Customer Return",
    titleEs: "Procesar una Devolución de Cliente",
    industry: "retail",
    level: "beginner",
    vocabulary: [
      {
        word: "receipt",
        pronunciation: "/rɪˈsiːt/",
        definitionEn: "A printed or digital proof of purchase",
        definitionEs: "Un comprobante impreso o digital de compra",
        example: "Do you have your receipt with you?",
      },
      {
        word: "exchange",
        pronunciation: "/ɪksˈtʃeɪndʒ/",
        definitionEn: "Swapping one item for another",
        definitionEs: "Cambiar un artículo por otro",
        example: "Would you like a refund or an exchange?",
      },
      {
        word: "store credit",
        pronunciation: "/stɔːr ˈkrɛdɪt/",
        definitionEn: "Credit to be used for future purchases at the store",
        definitionEs: "Crédito para usar en compras futuras en la tienda",
        example: "We can offer you store credit if you prefer.",
      },
    ],
    culturalNote:
      "In US retail, customers expect a smooth, no-hassle return process. Being apologetic and solution-focused keeps customers happy and coming back.",
    culturalNoteEs:
      "En el comercio minorista de EE.UU., los clientes esperan un proceso de devolución fácil. Ser empático y enfocado en soluciones mantiene a los clientes satisfechos.",
    lines: [
      {
        speaker: "Associate",
        role: "Retail Associate",
        roleEs: "Asociado de Ventas",
        text: "Hi! Welcome back. How can I help you today?",
        textEs: "¡Hola! Bienvenido. ¿En qué le puedo ayudar hoy?",
        tip: "'Welcome back' is a warm phrase for returning customers. Always greet with energy.",
        tipEs: "'Welcome back' es una frase cálida para clientes que regresan. Siempre salude con energía.",
      },
      {
        speaker: "Customer",
        role: "Customer",
        roleEs: "Cliente",
        text: "I'd like to return this jacket. I bought it last week, but the zipper is broken.",
        textEs: "Quisiera devolver esta chaqueta. La compré la semana pasada, pero el cierre está roto.",
        tip: "State the problem clearly. 'The zipper is broken' is direct and professional.",
        tipEs: "Diga el problema claramente. 'The zipper is broken' es directo y profesional.",
      },
      {
        speaker: "Associate",
        role: "Retail Associate",
        roleEs: "Asociado de Ventas",
        text: "I'm sorry to hear that. Do you have your receipt or the original packaging?",
        textEs: "Lo siento mucho. ¿Tiene su recibo o el empaque original?",
        tip: "'I'm sorry to hear that' shows empathy without accepting blame. Essential in customer service.",
        tipEs: "'I'm sorry to hear that' muestra empatía sin aceptar culpa. Esencial en servicio al cliente.",
      },
      {
        speaker: "Customer",
        role: "Customer",
        roleEs: "Cliente",
        text: "Yes, I have the receipt right here. I also still have the tags on it.",
        textEs: "Sí, aquí está el recibo. También tiene las etiquetas todavía.",
        tip: "'Right here' is a natural phrase when presenting something. Keeping tags on is key for US returns.",
        tipEs: "'Right here' es una frase natural al presentar algo. Mantener las etiquetas es clave para devoluciones en EE.UU.",
      },
      {
        speaker: "Associate",
        role: "Retail Associate",
        roleEs: "Asociado de Ventas",
        text: "Perfect. Would you prefer a full refund to your original payment method, or would you like to exchange it for another jacket?",
        textEs: "Perfecto. ¿Prefiere un reembolso completo a su método de pago original, o le gustaría cambiarlo por otra chaqueta?",
        tip: "Always give the customer options. 'Original payment method' is standard US retail language.",
        tipEs: "Siempre dé opciones al cliente. 'Original payment method' es lenguaje estándar del comercio en EE.UU.",
      },
      {
        speaker: "Customer",
        role: "Customer",
        roleEs: "Cliente",
        text: "I'll take the refund, please.",
        textEs: "Me gustaría el reembolso, por favor.",
        tip: "'I'll take the refund' is natural and decisive. Always add 'please' — it's polite.",
        tipEs: "'I'll take the refund' es natural y decisivo. Siempre agregue 'please' — es cortés.",
      },
    ],
  },
  {
    id: "technology-standup",
    title: "Daily Standup Meeting",
    titleEs: "Reunión Diaria de Standup",
    industry: "technology",
    level: "intermediate",
    vocabulary: [
      {
        word: "blocker",
        pronunciation: "/ˈblɒkər/",
        definitionEn: "An obstacle preventing progress on a task",
        definitionEs: "Un obstáculo que impide el progreso en una tarea",
        example: "I have a blocker — I'm waiting on the API credentials.",
      },
      {
        word: "sprint",
        pronunciation: "/sprɪnt/",
        definitionEn: "A short development cycle, usually 2 weeks",
        definitionEs: "Un ciclo corto de desarrollo, generalmente 2 semanas",
        example: "We're halfway through the sprint.",
      },
      {
        word: "deploy",
        pronunciation: "/dɪˈplɔɪ/",
        definitionEn: "To release software to a live environment",
        definitionEs: "Lanzar software a un entorno en vivo",
        example: "We'll deploy the fix to production tonight.",
      },
    ],
    culturalNote:
      "In US tech companies, the daily standup is 15 minutes max. Be concise. Use 'yesterday / today / blockers' format.",
    culturalNoteEs:
      "En empresas de tecnología en EE.UU., el standup diario dura máximo 15 minutos. Sea conciso. Use el formato 'ayer / hoy / bloqueadores'.",
    lines: [
      {
        speaker: "Scrum Master",
        role: "Scrum Master",
        roleEs: "Scrum Master",
        text: "Good morning everyone. Let's keep this quick. Who wants to go first?",
        textEs: "Buenos días a todos. Seamos rápidos. ¿Quién quiere empezar?",
        tip: "'Let's keep this quick' is a signal to be brief. Standup culture values conciseness above all.",
        tipEs: "'Let's keep this quick' es una señal de ser breve. La cultura de standup valora la concisión.",
      },
      {
        speaker: "Developer",
        role: "Software Developer",
        roleEs: "Desarrollador de Software",
        text: "I'll go. Yesterday I finished the login form validation. Today I'm starting the dashboard API integration. No blockers.",
        textEs: "Voy yo. Ayer terminé la validación del formulario de login. Hoy empiezo la integración de la API del dashboard. Sin bloqueadores.",
        tip: "The three-part standup format: what you did, what you'll do, any blockers. Always in that order.",
        tipEs: "El formato de standup en tres partes: qué hiciste, qué harás, algún bloqueador. Siempre en ese orden.",
      },
      {
        speaker: "Developer 2",
        role: "QA Engineer",
        roleEs: "Ingeniero de QA",
        text: "My turn. Yesterday I ran regression tests on the checkout flow — found two bugs, both logged in Jira. Today I'll test the new payment module. I do have one blocker: I need staging environment access.",
        textEs: "Mi turno. Ayer hice pruebas de regresión en el flujo de compra — encontré dos errores, ambos registrados en Jira. Hoy probaré el nuevo módulo de pagos. Sí tengo un bloqueador: necesito acceso al entorno de staging.",
        tip: "Always quantify your work — 'two bugs, both logged' sounds professional and accountable.",
        tipEs: "Siempre cuantifique su trabajo — 'two bugs, both logged' suena profesional y responsable.",
      },
      {
        speaker: "Scrum Master",
        role: "Scrum Master",
        roleEs: "Scrum Master",
        text: "Got it. I'll get you that access right after standup. Let's not let that blocker sit. Anyone else?",
        textEs: "Entendido. Te consigo ese acceso justo después del standup. No dejemos que ese bloqueador siga. ¿Alguien más?",
        tip: "'Let's not let that blocker sit' means resolve it fast. Shows urgency without panic.",
        tipEs: "'Let's not let that blocker sit' significa resolverlo rápido. Muestra urgencia sin pánico.",
      },
    ],
  },
  {
    id: "logistics-shipment",
    title: "Reporting a Shipment Discrepancy",
    titleEs: "Reportar una Discrepancia de Envío",
    industry: "logistics",
    level: "intermediate",
    vocabulary: [
      {
        word: "discrepancy",
        pronunciation: "/dɪˈskrɛpənsi/",
        definitionEn: "A difference between what was expected and what was received",
        definitionEs: "Una diferencia entre lo esperado y lo recibido",
        example: "There's a discrepancy in the shipment count.",
      },
      {
        word: "purchase order",
        pronunciation: "/ˈpɜːrtʃəs ˈɔːrdər/",
        definitionEn: "A document authorizing a purchase from a supplier",
        definitionEs: "Un documento que autoriza una compra a un proveedor",
        example: "Please match the delivery against the purchase order.",
      },
      {
        word: "claim",
        pronunciation: "/kleɪm/",
        definitionEn: "A formal request for compensation due to loss or damage",
        definitionEs: "Una solicitud formal de compensación por pérdida o daño",
        example: "We need to file a claim with the carrier.",
      },
    ],
    culturalNote:
      "In US logistics, documenting discrepancies immediately protects your company legally. Never sign off on a delivery without verifying the count.",
    culturalNoteEs:
      "En logística en EE.UU., documentar discrepancias de inmediato protege legalmente a su empresa. Nunca firme una entrega sin verificar el conteo.",
    lines: [
      {
        speaker: "Receiver",
        role: "Warehouse Receiver",
        roleEs: "Receptor de Almacén",
        text: "I need to report an issue with today's delivery. The purchase order shows 200 units, but we only received 180.",
        textEs: "Necesito reportar un problema con la entrega de hoy. La orden de compra muestra 200 unidades, pero solo recibimos 180.",
        tip: "State the facts clearly: reference the PO number and the specific discrepancy. No guessing.",
        tipEs: "Diga los hechos claramente: referencie el número de orden y la discrepancia específica. Sin suposiciones.",
      },
      {
        speaker: "Supervisor",
        role: "Logistics Supervisor",
        roleEs: "Supervisor de Logística",
        text: "Did you document the shortage before signing the delivery receipt?",
        textEs: "¿Documentó la faltante antes de firmar el recibo de entrega?",
        tip: "'Shortage' means fewer items than ordered. Documenting before signing is critical in US logistics.",
        tipEs: "'Shortage' significa menos artículos de lo ordenado. Documentar antes de firmar es crítico en logística de EE.UU.",
      },
      {
        speaker: "Receiver",
        role: "Warehouse Receiver",
        roleEs: "Receptor de Almacén",
        text: "Yes. I noted the shortage on the delivery receipt and took photos of the pallet. The driver also signed the note.",
        textEs: "Sí. Anoté la faltante en el recibo de entrega y tomé fotos del pallet. El conductor también firmó la nota.",
        tip: "Photos + signed note = strong documentation. This is best practice in US freight and logistics.",
        tipEs: "Fotos + nota firmada = documentación sólida. Esta es la mejor práctica en carga y logística en EE.UU.",
      },
      {
        speaker: "Supervisor",
        role: "Logistics Supervisor",
        roleEs: "Supervisor de Logística",
        text: "Good work. I'll contact the supplier and file a claim with the carrier. Can you email me the photos and the signed receipt?",
        textEs: "Buen trabajo. Contactaré al proveedor y presentaré un reclamo con el transportista. ¿Puede enviarme las fotos y el recibo firmado por correo?",
        tip: "'File a claim' means formally requesting compensation. Always say 'file a claim', not 'ask for money'.",
        tipEs: "'File a claim' significa solicitar compensación formalmente. Siempre diga 'file a claim', no 'ask for money'.",
      },
    ],
  },
  {
    id: "education-parent-conference",
    title: "Parent-Teacher Conference",
    titleEs: "Conferencia con Padres de Familia",
    industry: "education",
    level: "intermediate",
    vocabulary: [
      {
        word: "grade",
        pronunciation: "/ɡreɪd/",
        definitionEn: "A score or mark reflecting a student's performance",
        definitionEs: "Una calificación que refleja el desempeño de un estudiante",
        example: "Your son's grade in math has improved this semester.",
      },
      {
        word: "IEP",
        pronunciation: "/aɪ iː piː/",
        definitionEn: "Individualized Education Program — a plan for students with special needs",
        definitionEs: "Plan de Educación Individualizado — un plan para estudiantes con necesidades especiales",
        example: "We should discuss whether an IEP would benefit your child.",
      },
      {
        word: "benchmark",
        pronunciation: "/ˈbɛntʃmɑːrk/",
        definitionEn: "A standard level of achievement used for comparison",
        definitionEs: "Un nivel estándar de logro usado para comparar",
        example: "She is performing above the benchmark for her grade level.",
      },
    ],
    culturalNote:
      "In US schools, parent-teacher conferences are scheduled events. Teachers use encouraging, solution-focused language. Avoid blaming the child — focus on growth.",
    culturalNoteEs:
      "En escuelas de EE.UU., las conferencias con padres son eventos programados. Los maestros usan lenguaje alentador y enfocado en soluciones. Evite culpar al niño — enfóquese en el crecimiento.",
    lines: [
      {
        speaker: "Teacher",
        role: "Classroom Teacher",
        roleEs: "Maestra de Salón",
        text: "Thank you for coming in today, Mr. and Mrs. Flores. I appreciate you taking the time.",
        textEs: "Gracias por venir hoy, Sr. y Sra. Flores. Agradezco que se tomaran el tiempo.",
        tip: "Always thank parents for attending. This sets a respectful, collaborative tone from the start.",
        tipEs: "Siempre agradezca a los padres por asistir. Esto establece un tono de respeto y colaboración desde el inicio.",
      },
      {
        speaker: "Parent",
        role: "Parent",
        roleEs: "Padre de Familia",
        text: "Of course. We want to stay involved in our daughter's education. How is she doing overall?",
        textEs: "Por supuesto. Queremos estar involucrados en la educación de nuestra hija. ¿Cómo le está yendo en general?",
        tip: "'Stay involved' is a key phrase US teachers love to hear. Shows engagement and responsibility.",
        tipEs: "'Stay involved' es una frase clave que los maestros en EE.UU. aman escuchar. Muestra compromiso y responsabilidad.",
      },
      {
        speaker: "Teacher",
        role: "Classroom Teacher",
        roleEs: "Maestra de Salón",
        text: "Sofia is doing wonderfully in reading — she's above grade level. In math, she's meeting the benchmark but I believe she can go further with a bit more practice at home.",
        textEs: "Sofía está haciendo maravillosamente en lectura — está por encima del nivel de grado. En matemáticas, está cumpliendo el benchmark pero creo que puede avanzar más con un poco más de práctica en casa.",
        tip: "US teachers use the 'sandwich method': positive feedback, area to improve, positive close. Note it here.",
        tipEs: "Los maestros en EE.UU. usan el 'método sándwich': retroalimentación positiva, área a mejorar, cierre positivo. Nótelo aquí.",
      },
      {
        speaker: "Parent",
        role: "Parent",
        roleEs: "Padre de Familia",
        text: "What kind of activities would you recommend to help her at home?",
        textEs: "¿Qué tipo de actividades recomendaría para ayudarla en casa?",
        tip: "Asking for specific recommendations is proactive parenting in US culture — teachers respond very positively.",
        tipEs: "Pedir recomendaciones específicas es ser un padre proactivo en la cultura de EE.UU. — los maestros responden muy positivamente.",
      },
      {
        speaker: "Teacher",
        role: "Classroom Teacher",
        roleEs: "Maestra de Salón",
        text: "Even 15 minutes of math practice using apps like Khan Academy can make a big difference. I can send you a list of resources by email this week.",
        textEs: "Incluso 15 minutos de práctica de matemáticas con aplicaciones como Khan Academy puede hacer una gran diferencia. Puedo enviarle una lista de recursos por correo esta semana.",
        tip: "Offering to follow up by email shows professionalism. In US schools, email is the main communication tool.",
        tipEs: "Ofrecer dar seguimiento por correo muestra profesionalismo. En escuelas de EE.UU., el correo es la herramienta principal de comunicación.",
      },
    ],
  },
  {
    id: "hospitality-checkin",
    title: "Hotel Check-In",
    titleEs: "Check-In en el Hotel",
    industry: "hospitality",
    level: "beginner",
    vocabulary: [
      {
        word: "reservation",
        pronunciation: "/ˌrɛzərˈveɪʃən/",
        definitionEn: "A booking made in advance for a room or service",
        definitionEs: "Una reserva hecha con anticipación para una habitación o servicio",
        example: "I have a reservation under the name Garcia.",
      },
      {
        word: "amenities",
        pronunciation: "/əˈmiːnɪtiz/",
        definitionEn: "Hotel facilities and services provided to guests",
        definitionEs: "Instalaciones y servicios del hotel para los huéspedes",
        example: "Our amenities include a pool, gym, and complimentary breakfast.",
      },
      {
        word: "checkout",
        pronunciation: "/ˈtʃɛkaʊt/",
        definitionEn: "The process of leaving and paying when departing the hotel",
        definitionEs: "El proceso de salida y pago al dejar el hotel",
        example: "Checkout time is at 11 AM.",
      },
    ],
    culturalNote:
      "In US hotels, front desk agents are trained to be warm, efficient, and proactive. Upselling (offering room upgrades) is standard practice.",
    culturalNoteEs:
      "En hoteles de EE.UU., los agentes de recepción están entrenados para ser cálidos, eficientes y proactivos. Las ventas adicionales (ofrecer mejoras de habitación) son práctica estándar.",
    lines: [
      {
        speaker: "Front Desk",
        role: "Front Desk Agent",
        roleEs: "Agente de Recepción",
        text: "Welcome to the Grand Palms Hotel! Do you have a reservation with us?",
        textEs: "¡Bienvenido al Hotel Grand Palms! ¿Tiene una reserva con nosotros?",
        tip: "Use the hotel name in your greeting — it's professional and makes guests feel they arrived at the right place.",
        tipEs: "Use el nombre del hotel en su saludo — es profesional y hace que los huéspedes sientan que llegaron al lugar correcto.",
      },
      {
        speaker: "Guest",
        role: "Hotel Guest",
        roleEs: "Huésped del Hotel",
        text: "Yes, I have a reservation. The name is Ana Vargas. I booked a standard room for three nights.",
        textEs: "Sí, tengo una reserva. El nombre es Ana Vargas. Reservé una habitación estándar por tres noches.",
        tip: "State your name and booking details immediately. 'I booked' is the natural past tense for reservations.",
        tipEs: "Dé su nombre y detalles de reserva de inmediato. 'I booked' es el tiempo pasado natural para reservaciones.",
      },
      {
        speaker: "Front Desk",
        role: "Front Desk Agent",
        roleEs: "Agente de Recepción",
        text: "I found your reservation, Ms. Vargas. We actually have a king suite available at a discounted rate tonight. Would you like to upgrade?",
        textEs: "Encontré su reserva, Sra. Vargas. De hecho tenemos una suite king disponible a tarifa con descuento esta noche. ¿Le gustaría hacer una mejora?",
        tip: "'Would you like to upgrade?' is the professional upsell phrase. It's an offer, never pressure.",
        tipEs: "'Would you like to upgrade?' es la frase profesional de venta adicional. Es una oferta, nunca una presión.",
      },
      {
        speaker: "Guest",
        role: "Hotel Guest",
        roleEs: "Huésped del Hotel",
        text: "No, thank you. I'll stick with my original room. What time is checkout?",
        textEs: "No, gracias. Me quedaré con mi habitación original. ¿A qué hora es el checkout?",
        tip: "'I'll stick with...' means 'I'll keep my original choice'. A polite, natural way to decline an offer.",
        tipEs: "'I'll stick with...' significa 'mantendré mi elección original'. Una forma cortés y natural de rechazar una oferta.",
      },
      {
        speaker: "Front Desk",
        role: "Front Desk Agent",
        roleEs: "Agente de Recepción",
        text: "Checkout is at 11 AM. Here are your key cards. Your room is on the 4th floor — take the elevators on your left. Enjoy your stay!",
        textEs: "El checkout es a las 11 AM. Aquí están sus tarjetas llave. Su habitación está en el 4to piso — tome los elevadores a su izquierda. ¡Disfrute su estadía!",
        tip: "'Enjoy your stay!' is the standard closing phrase in hospitality. Always end with it.",
        tipEs: "'Enjoy your stay!' es la frase de cierre estándar en hotelería. Siempre termine con ella.",
      },
    ],
  },
  {
    id: "manufacturing-quality",
    title: "Quality Control Inspection",
    titleEs: "Inspección de Control de Calidad",
    industry: "manufacturing",
    level: "intermediate",
    vocabulary: [
      {
        word: "defect",
        pronunciation: "/ˈdiːfɛkt/",
        definitionEn: "A flaw or imperfection in a product",
        definitionEs: "Un defecto o imperfección en un producto",
        example: "This batch has a surface defect — we need to flag it.",
      },
      {
        word: "tolerance",
        pronunciation: "/ˈtɒlərəns/",
        definitionEn: "The allowable range of variation in a measurement",
        definitionEs: "El rango permitido de variación en una medición",
        example: "The part is within tolerance — it passes inspection.",
      },
      {
        word: "batch",
        pronunciation: "/bætʃ/",
        definitionEn: "A group of items produced at the same time",
        definitionEs: "Un grupo de artículos producidos al mismo tiempo",
        example: "We need to inspect the entire batch before shipping.",
      },
    ],
    culturalNote:
      "In US manufacturing, quality control is not just one person's job — everyone on the floor is responsible. Speaking up about defects is respected, not punished.",
    culturalNoteEs:
      "En manufactura en EE.UU., el control de calidad no es solo trabajo de una persona — todos en el piso son responsables. Hablar sobre defectos es respetado, no castigado.",
    lines: [
      {
        speaker: "QC Inspector",
        role: "Quality Control Inspector",
        roleEs: "Inspector de Control de Calidad",
        text: "I need to flag an issue with this batch. I'm seeing surface defects on approximately 15% of the parts.",
        textEs: "Necesito señalar un problema con este lote. Estoy viendo defectos superficiales en aproximadamente el 15% de las piezas.",
        tip: "'Flag an issue' is the professional phrase for reporting a problem. Quantify when possible (15%).",
        tipEs: "'Flag an issue' es la frase profesional para reportar un problema. Cuantifique cuando sea posible (15%).",
      },
      {
        speaker: "Supervisor",
        role: "Production Supervisor",
        roleEs: "Supervisor de Producción",
        text: "When did you first notice the defects? Was there any change in the production line today?",
        textEs: "¿Cuándo notó por primera vez los defectos? ¿Hubo algún cambio en la línea de producción hoy?",
        tip: "Root-cause questions are standard in US manufacturing. Expect them — be ready with specific details.",
        tipEs: "Las preguntas de causa raíz son estándar en manufactura en EE.UU. Espérelas — esté listo con detalles específicos.",
      },
      {
        speaker: "QC Inspector",
        role: "Quality Control Inspector",
        roleEs: "Inspector de Control de Calidad",
        text: "I noticed it about an hour ago, starting with unit 450. There was a tool change on press number 3 around that time.",
        textEs: "Lo noté hace aproximadamente una hora, comenzando con la unidad 450. Hubo un cambio de herramienta en la prensa número 3 alrededor de ese momento.",
        tip: "Give specific unit numbers and timestamps. This precision is highly valued in US manufacturing environments.",
        tipEs: "Dé números de unidad y tiempos específicos. Esta precisión es muy valorada en entornos de manufactura en EE.UU.",
      },
      {
        speaker: "Supervisor",
        role: "Production Supervisor",
        roleEs: "Supervisor de Producción",
        text: "Good catch. Stop the line on press 3 and quarantine units 450 through 600 for re-inspection. I'll have engineering take a look at the tool setup.",
        textEs: "Buen trabajo al detectarlo. Pare la línea en la prensa 3 y ponga en cuarentena las unidades 450 a 600 para re-inspección. Haré que ingeniería revise la configuración de la herramienta.",
        tip: "'Good catch' is high praise in manufacturing — it means you prevented a bigger problem. 'Quarantine' = isolate for inspection.",
        tipEs: "'Good catch' es un gran elogio en manufactura — significa que evitó un problema mayor. 'Quarantine' = aislar para inspección.",
      },
    ],
  },
  {
    id: "healthcare-adv-discharge",
    industry: "healthcare",
    level: "advanced",
    title: "Complex Patient Discharge Planning",
    titleEs: "Planificación de Alta Médica Compleja",
    lines: [
      {
        speaker: "Physician",
        role: "Attending Physician",
        roleEs: "Médico Titular",
        text: "Mr. Castillo is medically stable for discharge, but I want the team aligned on the disposition before we move forward. What's the current plan?",
        textEs: "El Sr. Castillo está médicamente estable para el alta, pero quiero que el equipo esté alineado en la disposición antes de avanzar. ¿Cuál es el plan actual?",
        tip: "'Medically stable' is a precise clinical phrase. 'Disposition' shows advanced vocabulary — it means where the patient goes next.",
        tipEs: "'Medically stable' es una frase clínica precisa. 'Disposition' muestra vocabulario avanzado — significa a dónde va el paciente.",
      },
      {
        speaker: "Case Manager",
        role: "Case Manager",
        roleEs: "Coordinadora de Casos",
        text: "He doesn't have sufficient support at home for wound care, and he lives alone. I've submitted a referral to a skilled nursing facility pending insurance authorization.",
        textEs: "No tiene suficiente apoyo en casa para el cuidado de heridas y vive solo. Envié una referencia a un centro de enfermería especializada pendiente de autorización del seguro.",
        tip: "'Pending insurance authorization' is standard US healthcare language — it means waiting for insurance to approve.",
        tipEs: "'Pending insurance authorization' es lenguaje estándar de salud en EE.UU. — significa esperando aprobación del seguro.",
      },
      {
        speaker: "Nurse",
        role: "Charge Nurse",
        roleEs: "Enfermera Encargada",
        text: "I can coordinate patient education on wound care today regardless of disposition. I'd also recommend a follow-up with cardiology within seven days given his ejection fraction.",
        textEs: "Puedo coordinar la educación del paciente sobre el cuidado de heridas hoy, independientemente de la disposición. También recomendaría seguimiento con cardiología en siete días dada su fracción de eyección.",
        tip: "'Ejection fraction' is advanced cardiology vocab. Using specialty terms correctly signals expertise.",
        tipEs: "'Ejection fraction' es vocabulario avanzado de cardiología. Usar términos especializados correctamente señala expertise.",
      },
      {
        speaker: "Physician",
        role: "Attending Physician",
        roleEs: "Médico Titular",
        text: "Agreed. Let's hold discharge until SNF authorization is confirmed — I'll update the orders. Please document everything in the discharge summary by end of round.",
        textEs: "De acuerdo. Retengamos el alta hasta que se confirme la autorización del centro de enfermería — actualizaré las órdenes. Por favor documenten todo en el resumen del alta al final de la ronda.",
        tip: "'Hold discharge' means delay the patient's release. 'End of round' refers to the end of physician rounds — a daily hospital routine.",
        tipEs: "'Hold discharge' significa retrasar el alta. 'End of round' se refiere al final de las rondas médicas — una rutina diaria en hospitales.",
      },
    ],
    vocabulary: [
      {
        word: "disposition",
        pronunciation: "/ˌdɪspəˈzɪʃən/",
        definitionEn: "The plan for where a patient goes after leaving the hospital",
        definitionEs: "El plan para a dónde va un paciente al salir del hospital",
        example: "What's the patient's disposition — home or skilled nursing?",
      },
      {
        word: "contraindication",
        pronunciation: "/ˌkɒntrəˌɪndɪˈkeɪʃən/",
        definitionEn: "A condition that makes a treatment inadvisable",
        definitionEs: "Una condición que hace inadvisable un tratamiento",
        example: "Anticoagulants are contraindicated given her history.",
      },
      {
        word: "follow-up",
        pronunciation: "/ˈfɒloʊ ʌp/",
        definitionEn: "A subsequent appointment to monitor progress after treatment",
        definitionEs: "Una cita posterior para monitorear el progreso tras el tratamiento",
        example: "Schedule a follow-up with cardiology within 7 days.",
      },
    ],
    culturalNote: "In US hospitals, discharge planning is a multidisciplinary process. Social workers, nurses, and physicians all coordinate. Use precise, evidence-based language.",
    culturalNoteEs: "En hospitales de EE.UU., la planificación del alta es un proceso multidisciplinario. Trabajadores sociales, enfermeros y médicos coordinan. Use lenguaje preciso y basado en evidencia.",
  },
  {
    id: "construction-adv-bid",
    industry: "construction",
    level: "advanced",
    title: "Subcontractor Bid Negotiation",
    titleEs: "Negociación de Propuesta de Subcontratista",
    lines: [
      {
        speaker: "GC",
        role: "General Contractor",
        roleEs: "Contratista General",
        text: "We've reviewed your bid and we're interested, but your number is about 12% above our budget. Can we talk about where there's flexibility?",
        textEs: "Revisamos su propuesta y estamos interesados, pero su cifra está aproximadamente un 12% por encima de nuestro presupuesto. ¿Podemos hablar de dónde hay flexibilidad?",
        tip: "'Your number' = your bid price. Asking 'where there's flexibility' is a professional negotiation opener — not a demand.",
        tipEs: "'Your number' = su precio de propuesta. Preguntar 'where there's flexibility' es una apertura profesional de negociación, no una exigencia.",
      },
      {
        speaker: "Sub",
        role: "Subcontractor",
        roleEs: "Subcontratista",
        text: "I appreciate the directness. The main cost driver is material — steel prices are up 18% from last quarter. I can sharpen the number if we adjust the payment schedule to net-15 instead of net-30.",
        textEs: "Agradezco la franqueza. El principal impulsor de costos es el material — los precios del acero subieron 18% del trimestre pasado. Puedo ajustar la cifra si modificamos el calendario de pagos a net-15 en vez de net-30.",
        tip: "'Net-15 / Net-30' means payment due in 15 or 30 days. Linking pricing to payment terms is a savvy negotiation move.",
        tipEs: "'Net-15 / Net-30' significa pago a 15 o 30 días. Vincular el precio a los términos de pago es una táctica de negociación inteligente.",
      },
      {
        speaker: "GC",
        role: "General Contractor",
        roleEs: "Contratista General",
        text: "Net-15 is workable if we're talking about a 7% reduction. But I also need a clear exclusions list in the contract — last project we had scope creep that wasn't defined upfront.",
        textEs: "Net-15 es posible si hablamos de una reducción del 7%. Pero también necesito una lista clara de exclusiones en el contrato — en el último proyecto tuvimos expansión de alcance que no estaba definida desde el inicio.",
        tip: "'Scope creep' = extra work that wasn't in the original contract. Defining exclusions prevents it. Key advanced construction term.",
        tipEs: "'Scope creep' = trabajo extra que no estaba en el contrato original. Definir exclusiones lo previene. Término avanzado clave de construcción.",
      },
      {
        speaker: "Sub",
        role: "Subcontractor",
        roleEs: "Subcontratista",
        text: "Fair enough. I can do 7% off with net-15, and I'll include a detailed exclusions and allowances schedule as a contract exhibit. I'd also need a mutual lien waiver at final payment.",
        textEs: "Justo. Puedo hacer el 7% de descuento con net-15, e incluiré un calendario detallado de exclusiones y allowances como anexo del contrato. También necesitaría una renuncia mutua de gravamen al pago final.",
        tip: "'Allowances' = budget items for items not fully defined yet. 'Mutual lien waiver' protects both parties at project close.",
        tipEs: "'Allowances' = partidas presupuestarias para elementos no completamente definidos. 'Mutual lien waiver' protege a ambas partes al cierre del proyecto.",
      },
    ],
    vocabulary: [
      {
        word: "scope of work",
        pronunciation: "/skoʊp əv wɜːrk/",
        definitionEn: "A detailed description of the work to be performed under a contract",
        definitionEs: "Una descripción detallada del trabajo a realizar bajo un contrato",
        example: "We need to align on the scope of work before pricing.",
      },
      {
        word: "contingency",
        pronunciation: "/kənˈtɪndʒənsi/",
        definitionEn: "A reserve budget for unexpected costs",
        definitionEs: "Un presupuesto de reserva para costos inesperados",
        example: "We've built in a 10% contingency for unforeseen conditions.",
      },
      {
        word: "lien",
        pronunciation: "/liːn/",
        definitionEn: "A legal claim against a property for unpaid work",
        definitionEs: "Una reclamación legal contra una propiedad por trabajo no pagado",
        example: "If payment is delayed beyond 30 days, we reserve the right to file a lien.",
      },
    ],
    culturalNote: "In US construction, negotiations are direct and contract-driven. Verbal agreements mean little — always get it in writing. Knowing lien rights is essential.",
    culturalNoteEs: "En construcción en EE.UU., las negociaciones son directas y basadas en contratos. Los acuerdos verbales valen poco — siempre obtenga todo por escrito. Conocer los derechos de gravamen es esencial.",
  },
  {
    id: "restaurant-adv-service",
    industry: "restaurant",
    level: "advanced",
    title: "Handling a High-Profile Reservation",
    titleEs: "Manejar una Reservación de Alto Perfil",
    lines: [
      {
        speaker: "Manager",
        role: "Floor Manager",
        roleEs: "Gerente de Piso",
        text: "Team, we have a VIP party of six arriving at 7:30 — a restaurant critic and their guests. Table 12 needs to be pristine. No substitutions, no delays, no comp dishes offered unless I authorize it.",
        textEs: "Equipo, tenemos un grupo VIP de seis personas llegando a las 7:30 — un crítico gastronómico y sus acompañantes. La mesa 12 debe estar impecable. Sin sustituciones, sin retrasos, sin platos de cortesía a menos que yo lo autorice.",
        tip: "'No comp dishes unless I authorize it' — 'comp' means complimentary/free. Managers control comps to avoid looking like you're trying to influence the review.",
        tipEs: "'No comp dishes unless I authorize it' — 'comp' significa cortesía/gratis. Los gerentes controlan los comps para no parecer que intentan influir en la reseña.",
      },
      {
        speaker: "Server",
        role: "Lead Server",
        roleEs: "Mesero Principal",
        text: "Understood. I've flagged a severe tree nut allergy for one guest. I've already alerted the kitchen and the allergy protocol is in place — separate prep surface, dedicated utensils.",
        textEs: "Entendido. He señalado una alergia grave a las nueces arbóreas para un huésped. Ya alerté a la cocina y el protocolo de alergias está activo — superficie de preparación separada, utensilios dedicados.",
        tip: "'Flagged' = identified and communicated in advance. A severe allergy proactively managed shows professional excellence.",
        tipEs: "'Flagged' = identificado y comunicado con anticipación. Una alergia grave manejada proactivamente muestra excelencia profesional.",
      },
      {
        speaker: "Manager",
        role: "Floor Manager",
        roleEs: "Gerente de Piso",
        text: "Good. I want a silent check-in every 10 minutes — no hovering, but be present. If their water glass drops below half, it gets filled. And nobody mentions what table they're at to other guests.",
        textEs: "Bien. Quiero un check-in silencioso cada 10 minutos — sin rondar, pero estén presentes. Si el vaso de agua baja de la mitad, se llena. Y nadie menciona en qué mesa están a otros huéspedes.",
        tip: "'Silent check-in' and 'no hovering' are fine dining service principles — presence without intrusiveness. Very US high-end restaurant culture.",
        tipEs: "'Silent check-in' y 'no hovering' son principios de servicio en alta gastronomía — presencia sin intrusión. Muy característico de la cultura de restaurantes de lujo en EE.UU.",
      },
      {
        speaker: "Server",
        role: "Lead Server",
        roleEs: "Mesero Principal",
        text: "Confirmed. I'll also coordinate with the sommelier on a pre-selected wine pairing to offer — nothing pushy, just a recommendation if they ask. Should I brief the busser as well?",
        textEs: "Confirmado. También coordinaré con el sumiller sobre un maridaje de vinos preseleccionado para ofrecer — nada agresivo, solo una recomendación si preguntan. ¿También debo informar al busser?",
        tip: "'Sommelier' = wine specialist. 'Busser' = support staff who clear tables. Knowing all team roles and coordinating them shows leadership.",
        tipEs: "'Sommelier' = especialista en vinos. 'Busser' = personal de apoyo que retira platos. Conocer todos los roles del equipo y coordinarlos muestra liderazgo.",
      },
    ],
    vocabulary: [
      {
        word: "VIP",
        pronunciation: "/viː aɪ piː/",
        definitionEn: "Very Important Person — a guest receiving special attention",
        definitionEs: "Persona Muy Importante — un huésped que recibe atención especial",
        example: "The VIP table requires personal attention from the manager.",
      },
      {
        word: "mise en place",
        pronunciation: "/miːz ɒn plɑːs/",
        definitionEn: "French kitchen term: everything in its place before service",
        definitionEs: "Término de cocina francés: todo en su lugar antes del servicio",
        example: "Make sure your mise en place is complete before the VIP arrives.",
      },
      {
        word: "allergy protocol",
        pronunciation: "/ˈælərʤi ˈproʊtəkɒl/",
        definitionEn: "A documented set of steps to prevent allergen exposure for a guest",
        definitionEs: "Un conjunto documentado de pasos para prevenir exposición a alérgenos",
        example: "We have an allergy protocol in place for the guest in table 4.",
      },
    ],
    culturalNote: "In US fine dining, VIP service is silent and anticipatory — guests should feel attended to before they ask. Every detail is communicated from manager to floor in advance.",
    culturalNoteEs: "En la alta gastronomía de EE.UU., el servicio VIP es silencioso y anticipatorio — los huéspedes deben sentirse atendidos antes de pedir. Cada detalle se comunica del gerente al piso con antelación.",
  },
  {
    id: "office-adv-performance",
    industry: "office",
    level: "advanced",
    title: "Delivering a Performance Review",
    titleEs: "Entrega de una Evaluación de Desempeño",
    lines: [
      {
        speaker: "Manager",
        role: "Department Manager",
        roleEs: "Gerente de Departamento",
        text: "Thank you for coming in, Elena. I want to frame this as a two-way conversation — your self-assessment was thoughtful, and I want to make sure we're aligned before I share the formal rating.",
        textEs: "Gracias por venir, Elena. Quiero enmarcar esto como una conversación bidireccional — tu autoevaluación fue reflexiva y quiero asegurarme de que estemos alineados antes de compartir la calificación formal.",
        tip: "'Two-way conversation' signals psychological safety — it's a best-practice management phrase that invites the employee to speak openly.",
        tipEs: "'Two-way conversation' señala seguridad psicológica — es una frase de gestión de mejores prácticas que invita al empleado a hablar abiertamente.",
      },
      {
        speaker: "Employee",
        role: "Senior Analyst",
        roleEs: "Analista Senior",
        text: "I appreciate that. I feel I've exceeded targets on the Q3 campaign, but I struggled with cross-functional communication — I know that's a development area for me.",
        textEs: "Lo agradezco. Siento que superé los objetivos en la campaña del T3, pero tuve dificultades con la comunicación interfuncional — sé que es un área de desarrollo para mí.",
        tip: "Naming your own weakness before your manager does is a strong professional move. 'Development area' is a softer, growth-oriented way to say 'weakness'.",
        tipEs: "Nombrar tu propia debilidad antes de que lo haga tu gerente es un movimiento profesional fuerte. 'Development area' es una forma más suave y orientada al crecimiento de decir 'debilidad'.",
      },
      {
        speaker: "Manager",
        role: "Department Manager",
        roleEs: "Gerente de Departamento",
        text: "That's a fair self-assessment. Your Q3 results were outstanding — 140% of target. On the cross-functional side, I've heard similar feedback from the product team. I'd like to build a development plan around that.",
        textEs: "Esa es una autoevaluación justa. Tus resultados del T3 fueron sobresalientes — 140% del objetivo. En el lado interfuncional, he escuchado comentarios similares del equipo de producto. Me gustaría construir un plan de desarrollo en torno a eso.",
        tip: "'Development plan' = a formal document outlining steps to improve a specific skill. It's constructive, not punitive.",
        tipEs: "'Development plan' = un documento formal que detalla pasos para mejorar una habilidad específica. Es constructivo, no punitivo.",
      },
      {
        speaker: "Employee",
        role: "Senior Analyst",
        roleEs: "Analista Senior",
        text: "I'd welcome that. Could we include some stretch assignments in the plan? I want to be considered for the team lead role when it opens up, and I think cross-functional exposure would help.",
        textEs: "Lo recibiría bien. ¿Podríamos incluir algunas asignaciones desafiantes en el plan? Quiero ser considerada para el rol de líder de equipo cuando se abra, y creo que la exposición interfuncional ayudaría.",
        tip: "'Stretch assignments' = tasks beyond your current level, designed to grow your skills. Mentioning career goals during reviews is encouraged in US workplaces.",
        tipEs: "'Stretch assignments' = tareas más allá de tu nivel actual, diseñadas para desarrollar habilidades. Mencionar objetivos de carrera durante las evaluaciones es alentado en los lugares de trabajo de EE.UU.",
      },
    ],
    vocabulary: [
      {
        word: "performance review",
        pronunciation: "/pərˈfɔːrməns rɪˈvjuː/",
        definitionEn: "A formal evaluation of an employee's work over a period",
        definitionEs: "Una evaluación formal del trabajo de un empleado durante un período",
        example: "Her performance review highlighted both strengths and growth areas.",
      },
      {
        word: "stretch assignment",
        pronunciation: "/strɛtʃ əˈsaɪnmənt/",
        definitionEn: "A challenging task designed to develop new skills beyond current role",
        definitionEs: "Una tarea desafiante diseñada para desarrollar nuevas habilidades más allá del rol actual",
        example: "Leading the product launch was a stretch assignment that accelerated her growth.",
      },
      {
        word: "cross-functional",
        pronunciation: "/krɒs ˈfʌŋkʃənəl/",
        definitionEn: "Involving collaboration across different departments or teams",
        definitionEs: "Que implica colaboración entre diferentes departamentos o equipos",
        example: "The cross-functional team included marketing, engineering, and finance.",
      },
    ],
    culturalNote: "In US workplaces, performance reviews are structured conversations, not lectures. Employees are expected to self-assess and advocate for their careers. Silence is seen as disengagement.",
    culturalNoteEs: "En los lugares de trabajo de EE.UU., las evaluaciones de desempeño son conversaciones estructuradas, no conferencias. Se espera que los empleados se autoevalúen y aboguen por sus carreras. El silencio se interpreta como desinterés.",
  },
  {
    id: "retail-adv-inventory",
    industry: "retail",
    level: "advanced",
    title: "Managing a Shrink Investigation",
    titleEs: "Gestión de una Investigación de Merma",
    lines: [
      {
        speaker: "Loss Prevention",
        role: "Loss Prevention Manager",
        roleEs: "Gerente de Prevención de Pérdidas",
        text: "Our shrink rate this quarter is 2.4%, which is above the 1.8% threshold. Inventory reconciliation shows the variance is concentrated in the electronics aisle. I need to walk through the audit findings with you.",
        textEs: "Nuestra tasa de merma este trimestre es del 2.4%, por encima del umbral del 1.8%. La conciliación de inventario muestra que la variación se concentra en el pasillo de electrónica. Necesito repasar los hallazgos de la auditoría contigo.",
        tip: "'Shrink' = inventory loss from theft, damage, or error. 'Variance' = the gap between expected and actual stock. Both are key retail loss prevention terms.",
        tipEs: "'Shrink' = pérdida de inventario por robo, daño o error. 'Variance' = la brecha entre el stock esperado y el real. Ambos son términos clave de prevención de pérdidas en retail.",
      },
      {
        speaker: "Store Manager",
        role: "Store Manager",
        roleEs: "Gerente de Tienda",
        text: "I suspected as much. We've had two cashier terminations recently and cycle counts have been inconsistent. Could some of this be attributed to process gaps rather than external theft?",
        textEs: "Lo sospechaba. Tuvimos dos terminaciones de cajeros recientemente y los conteos cíclicos han sido inconsistentes. ¿Podría parte de esto atribuirse a brechas de proceso más que a robo externo?",
        tip: "'Cycle counts' = regular partial inventory checks rather than full counts. 'Process gaps' shows analytical thinking — not everything is theft.",
        tipEs: "'Cycle counts' = verificaciones parciales regulares de inventario en lugar de conteos completos. 'Process gaps' muestra pensamiento analítico — no todo es robo.",
      },
      {
        speaker: "Loss Prevention",
        role: "Loss Prevention Manager",
        roleEs: "Gerente de Prevención de Pérdidas",
        text: "A portion likely is. Footage review shows two external incidents in the past 30 days, but I also flagged a pattern in transaction voids at register 4 during the overnight shift. We need to pull those logs.",
        textEs: "Una parte probablemente sí lo es. La revisión de grabaciones muestra dos incidentes externos en los últimos 30 días, pero también identifiqué un patrón en anulaciones de transacciones en la caja 4 durante el turno nocturno. Necesitamos obtener esos registros.",
        tip: "'Transaction voids' = cancelled sales. Unusual void patterns can indicate employee theft. 'Footage review' = watching security camera recordings.",
        tipEs: "'Transaction voids' = ventas canceladas. Patrones inusuales de anulaciones pueden indicar robo de empleados. 'Footage review' = revisión de grabaciones de cámaras de seguridad.",
      },
      {
        speaker: "Store Manager",
        role: "Store Manager",
        roleEs: "Gerente de Tienda",
        text: "I'll authorize immediate access to the POS logs. In the meantime, should we increase floor coverage in electronics and implement a two-person integrity check on high-value SKUs?",
        textEs: "Autorizaré acceso inmediato a los registros del POS. Mientras tanto, ¿deberíamos aumentar la cobertura en el piso de electrónica e implementar una verificación de integridad de dos personas en los SKUs de alto valor?",
        tip: "'POS logs' = Point of Sale transaction records. 'Two-person integrity check' = requiring two staff to handle high-value items — a loss prevention best practice.",
        tipEs: "'POS logs' = registros de transacciones del Punto de Venta. 'Two-person integrity check' = requerir dos empleados para manejar artículos de alto valor — una mejor práctica de prevención de pérdidas.",
      },
    ],
    vocabulary: [
      {
        word: "shrink",
        pronunciation: "/ʃrɪŋk/",
        definitionEn: "Inventory loss due to theft, damage, administrative error, or fraud",
        definitionEs: "Pérdida de inventario por robo, daño, error administrativo o fraude",
        example: "The store reduced shrink by 30% after installing new camera systems.",
      },
      {
        word: "cycle count",
        pronunciation: "/ˈsaɪkəl kaʊnt/",
        definitionEn: "A routine partial inventory audit of specific items or areas",
        definitionEs: "Una auditoría parcial rutinaria de inventario de artículos o áreas específicas",
        example: "We do cycle counts on high-theft items every Monday.",
      },
      {
        word: "transaction void",
        pronunciation: "/trænˈzækʃən vɔɪd/",
        definitionEn: "A cancelled sale transaction at the point of sale",
        definitionEs: "Una transacción de venta cancelada en el punto de venta",
        example: "Multiple transaction voids by the same cashier triggered an investigation.",
      },
    ],
    culturalNote: "In US retail, loss prevention investigations must balance legal compliance with employee rights. Accusations require documented evidence. Managers are trained to be investigative, not accusatory.",
    culturalNoteEs: "En el retail de EE.UU., las investigaciones de prevención de pérdidas deben equilibrar el cumplimiento legal con los derechos de los empleados. Las acusaciones requieren evidencia documentada. Los gerentes están entrenados para ser investigativos, no acusatorios.",
  },
  {
    id: "technology-adv-incident",
    industry: "technology",
    level: "advanced",
    title: "Production Incident Response",
    titleEs: "Respuesta a un Incidente de Producción",
    lines: [
      {
        speaker: "On-Call Engineer",
        role: "On-Call Engineer",
        roleEs: "Ingeniero de Guardia",
        text: "We have a P1 incident — the payment service is throwing 503s and error rate is at 18%. I've declared an incident and opened the war room channel. Who's the incident commander?",
        textEs: "Tenemos un incidente P1 — el servicio de pagos está generando errores 503 y la tasa de errores está al 18%. Declaré un incidente y abrí el canal de sala de guerra. ¿Quién es el comandante del incidente?",
        tip: "'P1' = Priority 1, the most critical incident level. '503' = HTTP error meaning service unavailable. 'War room' = a dedicated channel for incident coordination.",
        tipEs: "'P1' = Prioridad 1, el nivel de incidente más crítico. '503' = error HTTP que significa servicio no disponible. 'War room' = un canal dedicado para la coordinación de incidentes.",
      },
      {
        speaker: "Tech Lead",
        role: "Tech Lead",
        roleEs: "Líder Técnico",
        text: "I'll take incident command. First — let's establish a timeline. When did the error rate start climbing? And can someone check if this correlates with the deployment we pushed at 14:23?",
        textEs: "Tomaré el mando del incidente. Primero — establezcamos una línea de tiempo. ¿Cuándo empezó a subir la tasa de errores? ¿Y alguien puede verificar si esto se correlaciona con el despliegue que enviamos a las 14:23?",
        tip: "'Incident command' = the role that coordinates all responders. Establishing a timeline is always the first step — it helps isolate the root cause.",
        tipEs: "'Incident command' = el rol que coordina a todos los respondedores. Establecer una línea de tiempo siempre es el primer paso — ayuda a aislar la causa raíz.",
      },
      {
        speaker: "On-Call Engineer",
        role: "On-Call Engineer",
        roleEs: "Ingeniero de Guardia",
        text: "Error rate began at 14:31 — eight minutes after the deployment. Logs show a null pointer exception in the payment gateway adapter. This looks like the deployment is the likely culprit.",
        textEs: "La tasa de errores comenzó a las 14:31 — ocho minutos después del despliegue. Los registros muestran una excepción de puntero nulo en el adaptador del gateway de pagos. Parece que el despliegue es el probable culpable.",
        tip: "'Null pointer exception' = a common code error where software tries to use a reference that points to nothing. 'Culprit' in tech context = the cause of the failure.",
        tipEs: "'Null pointer exception' = un error de código común donde el software intenta usar una referencia que apunta a nada. 'Culprit' en contexto técnico = la causa del fallo.",
      },
      {
        speaker: "Tech Lead",
        role: "Tech Lead",
        roleEs: "Líder Técnico",
        text: "Initiate a rollback on the payment service immediately — don't wait for a fix. Once we're stable, we'll do a full post-mortem. I want a draft ready within 24 hours with contributing factors and action items.",
        textEs: "Inicie un rollback en el servicio de pagos de inmediato — no espere a una corrección. Una vez que estemos estables, haremos un post-mortem completo. Quiero un borrador listo en 24 horas con factores contribuyentes y elementos de acción.",
        tip: "'Rollback' = reverting to the previous working version. 'Post-mortem' = a blameless review after an incident to learn and prevent recurrence. Standard US tech company practice.",
        tipEs: "'Rollback' = revertir a la versión anterior que funcionaba. 'Post-mortem' = una revisión sin culpas después de un incidente para aprender y prevenir recurrencias. Práctica estándar en empresas tecnológicas de EE.UU.",
      },
    ],
    vocabulary: [
      {
        word: "post-mortem",
        pronunciation: "/poʊst ˈmɔːrtəm/",
        definitionEn: "A blameless review after an incident to identify causes and prevent recurrence",
        definitionEs: "Una revisión sin culpas después de un incidente para identificar causas y prevenir recurrencias",
        example: "The post-mortem revealed three contributing factors to the outage.",
      },
      {
        word: "rollback",
        pronunciation: "/ˈroʊlbæk/",
        definitionEn: "Reverting software to a previous stable version after a failed deployment",
        definitionEs: "Revertir el software a una versión estable anterior después de un despliegue fallido",
        example: "We executed a rollback within 10 minutes to restore service.",
      },
      {
        word: "incident commander",
        pronunciation: "/ˈɪnsɪdənt kəˈmɑːndər/",
        definitionEn: "The person coordinating all responders during a production incident",
        definitionEs: "La persona que coordina a todos los respondedores durante un incidente de producción",
        example: "The incident commander kept the war room focused and updated stakeholders every 15 minutes.",
      },
    ],
    culturalNote: "In US tech companies, incident response is a formal, blameless process. Speed of mitigation matters more than finding fault. Post-mortems are learning tools, not punishment.",
    culturalNoteEs: "En las empresas tecnológicas de EE.UU., la respuesta a incidentes es un proceso formal y sin culpas. La velocidad de mitigación importa más que encontrar un culpable. Los post-mortems son herramientas de aprendizaje, no de castigo.",
  },
  {
    id: "logistics-adv-customs",
    industry: "logistics",
    level: "advanced",
    title: "Navigating a Customs Delay",
    titleEs: "Navegando un Retraso Aduanero",
    lines: [
      {
        speaker: "Logistics Manager",
        role: "Logistics Manager",
        roleEs: "Gerente de Logística",
        text: "The shipment from our Monterrey facility has been held at the Laredo port of entry for 72 hours. CBP flagged it for a secondary examination. Do we know the basis for the hold?",
        textEs: "El envío de nuestra instalación en Monterrey ha estado retenido en el puerto de entrada de Laredo por 72 horas. La CBP lo marcó para un examen secundario. ¿Sabemos la base de la retención?",
        tip: "'CBP' = US Customs and Border Protection. 'Secondary examination' = a more detailed inspection beyond the standard check. Knowing agency names signals expertise.",
        tipEs: "'CBP' = Protección Aduanera y Fronteriza de EE.UU. 'Secondary examination' = una inspección más detallada más allá de la verificación estándar. Conocer los nombres de las agencias señala expertise.",
      },
      {
        speaker: "Customs Broker",
        role: "Licensed Customs Broker",
        roleEs: "Agente Aduanal Certificado",
        text: "The hold is tied to a tariff classification discrepancy. The HS code filed doesn't match the product description on the commercial invoice. We need to submit a CF-28 request for information response within 5 business days or face additional penalties.",
        textEs: "La retención está relacionada con una discrepancia en la clasificación arancelaria. El código HS presentado no coincide con la descripción del producto en la factura comercial. Necesitamos enviar una respuesta CF-28 de solicitud de información dentro de 5 días hábiles o enfrentar penalizaciones adicionales.",
        tip: "'HS code' = Harmonized System code — an international product classification number for customs. 'CF-28' is a CBP form. This is advanced trade compliance vocabulary.",
        tipEs: "'HS code' = código del Sistema Armonizado — un número internacional de clasificación de productos para aduana. 'CF-28' es un formulario de la CBP. Este es vocabulario avanzado de cumplimiento comercial.",
      },
      {
        speaker: "Logistics Manager",
        role: "Logistics Manager",
        roleEs: "Gerente de Logística",
        text: "This is the third classification issue this year — we need to do a full HS code audit on our product catalog. In the meantime, what's the fastest path to release? Can we request an immediate examination appointment?",
        textEs: "Este es el tercer problema de clasificación este año — necesitamos hacer una auditoría completa de códigos HS en nuestro catálogo de productos. Mientras tanto, ¿cuál es el camino más rápido para el despacho? ¿Podemos solicitar una cita de examen inmediato?",
        tip: "'Release' in customs = when CBP allows the shipment to proceed. 'Examination appointment' = scheduling the physical inspection to speed up the process.",
        tipEs: "'Release' en aduanas = cuando la CBP permite que el envío proceda. 'Examination appointment' = programar la inspección física para acelerar el proceso.",
      },
      {
        speaker: "Customs Broker",
        role: "Licensed Customs Broker",
        roleEs: "Agente Aduanal Certificado",
        text: "I can request an exam appointment and submit the CF-28 response simultaneously. If we can provide binding rulings documentation for similar products, that strengthens our case significantly. I'll need the technical specs from your compliance team today.",
        textEs: "Puedo solicitar una cita de examen y enviar la respuesta CF-28 simultáneamente. Si podemos proporcionar documentación de resoluciones vinculantes para productos similares, eso fortalece significativamente nuestro caso. Necesitaré las especificaciones técnicas de su equipo de cumplimiento hoy.",
        tip: "'Binding ruling' = an official CBP decision on how a product should be classified. Having one on file gives your broker strong legal ground during disputes.",
        tipEs: "'Binding ruling' = una decisión oficial de la CBP sobre cómo debe clasificarse un producto. Tener una archivada le da a su agente una base legal sólida durante disputas.",
      },
    ],
    vocabulary: [
      {
        word: "HS code",
        pronunciation: "/eɪtʃ ɛs koʊd/",
        definitionEn: "Harmonized System code — a standardized international number classifying traded products",
        definitionEs: "Código del Sistema Armonizado — un número internacional estandarizado que clasifica los productos comercializados",
        example: "An incorrect HS code caused a 3-day customs delay and a $4,000 penalty.",
      },
      {
        word: "customs broker",
        pronunciation: "/ˈkʌstəmz ˈbroʊkər/",
        definitionEn: "A licensed professional who handles customs documentation and clearance on behalf of importers",
        definitionEs: "Un profesional licenciado que maneja la documentación y el despacho aduanero en nombre de los importadores",
        example: "Our customs broker filed all documents before the shipment arrived at the port.",
      },
      {
        word: "binding ruling",
        pronunciation: "/ˈbaɪndɪŋ ˈruːlɪŋ/",
        definitionEn: "An official CBP determination on the classification or duty rate for a specific product",
        definitionEs: "Una determinación oficial de la CBP sobre la clasificación o tasa arancelaria de un producto específico",
        example: "We obtained a binding ruling to avoid future classification disputes.",
      },
    ],
    culturalNote: "US customs compliance is highly technical and legally binding. Errors cost money and delay supply chains. Working with a licensed customs broker and maintaining accurate HS codes is standard practice for importers.",
    culturalNoteEs: "El cumplimiento aduanero en EE.UU. es altamente técnico y legalmente vinculante. Los errores cuestan dinero y retrasan las cadenas de suministro. Trabajar con un agente aduanal certificado y mantener códigos HS precisos es práctica estándar para los importadores.",
  },
  {
    id: "education-adv-iep",
    industry: "education",
    level: "advanced",
    title: "IEP Team Meeting",
    titleEs: "Reunión del Equipo de PEI",
    lines: [
      {
        speaker: "Special Ed Coordinator",
        role: "Special Education Coordinator",
        roleEs: "Coordinadora de Educación Especial",
        text: "Thank you all for being here for Marcus's annual IEP review. We're here to evaluate progress toward last year's goals and develop new measurable objectives for the coming year. Parents, your input is central to this process.",
        textEs: "Gracias a todos por estar aquí para la revisión anual del PEI de Marcus. Estamos aquí para evaluar el progreso hacia los objetivos del año pasado y desarrollar nuevos objetivos medibles para el próximo año. Padres, su aportación es central en este proceso.",
        tip: "'IEP' = Individualized Education Program — a federally required plan for students with disabilities. 'Annual review' = the mandatory yearly meeting to reassess it.",
        tipEs: "'IEP' = Programa de Educación Individualizado — un plan requerido federalmente para estudiantes con discapacidades. 'Annual review' = la reunión anual obligatoria para reevaluarlo.",
      },
      {
        speaker: "Parent",
        role: "Parent",
        roleEs: "Padre de Familia",
        text: "We've seen real growth in reading at home, but Marcus still gets very anxious during timed assessments. Can his accommodations be updated to include extended time and a separate testing environment?",
        textEs: "Hemos visto un crecimiento real en la lectura en casa, pero Marcus todavía se pone muy ansioso durante las evaluaciones cronometradas. ¿Pueden actualizarse sus acomodaciones para incluir tiempo extendido y un ambiente de examen separado?",
        tip: "'Accommodations' = changes to how a student is taught or tested, not what they learn. 'Extended time' and 'separate testing environment' are the most common IEP accommodations in US schools.",
        tipEs: "'Accommodations' = cambios en cómo se enseña o evalúa a un estudiante, no en lo que aprende. 'Extended time' y 'separate testing environment' son las acomodaciones de PEI más comunes en escuelas de EE.UU.",
      },
      {
        speaker: "Special Ed Teacher",
        role: "Special Education Teacher",
        roleEs: "Maestra de Educación Especial",
        text: "His progress data supports that request. Marcus met 4 of 6 annual goals. On the two unmet goals, I'd recommend we revise the benchmarks rather than carry them forward unchanged — they may need to be broken into smaller objectives.",
        textEs: "Los datos de progreso respaldan esa solicitud. Marcus cumplió 4 de 6 objetivos anuales. En los dos objetivos no cumplidos, recomendaría revisar los puntos de referencia en lugar de llevarlos adelante sin cambios — puede que necesiten dividirse en objetivos más pequeños.",
        tip: "'Progress data' = documented evidence of a student's improvement. 'Benchmarks' = intermediate milestones within a larger goal. Revising goals is normal and encouraged.",
        tipEs: "'Progress data' = evidencia documentada del progreso de un estudiante. 'Benchmarks' = hitos intermedios dentro de un objetivo mayor. Revisar los objetivos es normal y alentado.",
      },
      {
        speaker: "Special Ed Coordinator",
        role: "Special Education Coordinator",
        roleEs: "Coordinadora de Educación Especial",
        text: "Agreed. We'll add extended time and separate testing to the accommodations section and revise the two goals with new benchmarks. I'll circulate the updated draft within 5 school days for signatures. Everyone has the right to request a copy.",
        textEs: "De acuerdo. Agregaremos tiempo extendido y examen separado a la sección de acomodaciones y revisaremos los dos objetivos con nuevos puntos de referencia. Circularé el borrador actualizado dentro de 5 días escolares para firmas. Todos tienen derecho a solicitar una copia.",
        tip: "IEP documents are legal. Mentioning signature rights and the right to a copy is not just courtesy — it's legally required under IDEA (Individuals with Disabilities Education Act).",
        tipEs: "Los documentos del PEI son legales. Mencionar los derechos de firma y el derecho a una copia no es solo cortesía — es legalmente requerido bajo IDEA (Ley de Educación para Personas con Discapacidades).",
      },
    ],
    vocabulary: [
      {
        word: "IEP",
        pronunciation: "/aɪ iː piː/",
        definitionEn: "Individualized Education Program — a legal document outlining special education services for a student",
        definitionEs: "Programa de Educación Individualizado — un documento legal que describe los servicios de educación especial para un estudiante",
        example: "The IEP team met to review the student's progress and set new annual goals.",
      },
      {
        word: "accommodation",
        pronunciation: "/əˌkɒməˈdeɪʃən/",
        definitionEn: "A modification to how a student learns or is assessed, without changing the curriculum",
        definitionEs: "Una modificación sobre cómo aprende o es evaluado un estudiante, sin cambiar el currículo",
        example: "Extended time and a quiet room are common accommodations for students with anxiety.",
      },
      {
        word: "benchmark",
        pronunciation: "/ˈbɛntʃmɑːrk/",
        definitionEn: "A measurable milestone used to track progress toward a larger goal",
        definitionEs: "Un hito medible utilizado para rastrear el progreso hacia un objetivo mayor",
        example: "The IEP includes quarterly benchmarks to monitor reading fluency.",
      },
    ],
    culturalNote: "IEP meetings in the US are legally protected processes under federal law (IDEA). Parents are equal team members, not observers. Schools must follow IEP timelines and document everything. Knowing your rights is empowering.",
    culturalNoteEs: "Las reuniones del PEI en EE.UU. son procesos legalmente protegidos bajo la ley federal (IDEA). Los padres son miembros iguales del equipo, no observadores. Las escuelas deben seguir los plazos del PEI y documentar todo. Conocer sus derechos es empoderador.",
  },
  {
    id: "hospitality-adv-complaint",
    industry: "hospitality",
    level: "advanced",
    title: "Resolving a High-Stakes Guest Complaint",
    titleEs: "Resolver una Queja de Huésped de Alto Impacto",
    lines: [
      {
        speaker: "Guest",
        role: "Hotel Guest",
        roleEs: "Huésped del Hotel",
        text: "This is completely unacceptable. I booked a suite with a city view for my anniversary and I was given a standard room facing the parking structure. I want to speak with the general manager immediately.",
        textEs: "Esto es completamente inaceptable. Reservé una suite con vista a la ciudad para mi aniversario y me dieron una habitación estándar con vista al estacionamiento. Quiero hablar con el gerente general de inmediato.",
        tip: "'Facing the parking structure' vs 'city view' = a significant room downgrade. Requesting the GM is an escalation. Respond with calm acknowledgment — never defensiveness.",
        tipEs: "'Facing the parking structure' vs 'city view' = una rebaja significativa de habitación. Solicitar al GM es una escalada. Responde con reconocimiento tranquilo — nunca con defensividad.",
      },
      {
        speaker: "Front Desk Manager",
        role: "Front Desk Manager",
        roleEs: "Gerente de Recepción",
        text: "I completely understand your frustration, and I sincerely apologize — this should not have happened, especially on such a special occasion. I'm the Front Desk Manager and I have full authority to resolve this tonight. May I take a moment to review your reservation?",
        textEs: "Entiendo completamente su frustración y me disculpo sinceramente — esto no debería haber sucedido, especialmente en una ocasión tan especial. Soy el Gerente de Recepción y tengo plena autoridad para resolver esto esta noche. ¿Me permite un momento para revisar su reservación?",
        tip: "Acknowledging the occasion ('special occasion'), apologizing without excuse-making, and asserting your authority ('I have full authority') are the three keys to de-escalation in US hospitality.",
        tipEs: "Reconocer la ocasión ('special occasion'), disculparse sin dar excusas y afirmar su autoridad ('I have full authority') son las tres claves para la desescalada en la hospitalidad de EE.UU.",
      },
      {
        speaker: "Front Desk Manager",
        role: "Front Desk Manager",
        roleEs: "Gerente de Recepción",
        text: "I can see the suite was reserved and the system assigned the wrong room at check-in. I have a city-view junior suite available right now — it's slightly smaller than the full suite but offers the same panoramic view. I'd like to upgrade you at no additional charge and comp your first night's minibar.",
        textEs: "Puedo ver que la suite fue reservada y el sistema asignó la habitación incorrecta en el check-in. Tengo una junior suite con vista a la ciudad disponible ahora mismo — es un poco más pequeña que la suite completa pero ofrece la misma vista panorámica. Me gustaría mejorarle sin costo adicional y obsequiarle el minibar de la primera noche.",
        tip: "Offering a tangible remedy immediately — upgrade + comp — without waiting to be asked is the gold standard in US luxury hospitality service recovery.",
        tipEs: "Ofrecer un remedio tangible de inmediato — mejora + cortesía — sin esperar a que se solicite es el estándar de oro en la recuperación del servicio de hospitalidad de lujo en EE.UU.",
      },
      {
        speaker: "Guest",
        role: "Hotel Guest",
        roleEs: "Huésped del Hotel",
        text: "I appreciate that. I do want to make sure something like this doesn't happen to others — will this be flagged in your system so future reservations are protected?",
        textEs: "Lo agradezco. Quiero asegurarme de que algo así no le suceda a otros — ¿se señalará esto en su sistema para que las reservaciones futuras estén protegidas?",
        tip: "A guest asking that others are protected — not just themselves — is a sign they've been won over. Confirm process improvement to close the loop professionally.",
        tipEs: "Un huésped que pregunta que otros estén protegidos — no solo ellos mismos — es una señal de que han sido ganados. Confirme la mejora del proceso para cerrar profesionalmente.",
      },
    ],
    vocabulary: [
      {
        word: "service recovery",
        pronunciation: "/ˈsɜːrvɪs rɪˈkʌvəri/",
        definitionEn: "The process of turning a negative guest experience into a positive one through resolution",
        definitionEs: "El proceso de convertir una experiencia negativa del huésped en positiva mediante la resolución",
        example: "Effective service recovery often results in stronger loyalty than if no problem had occurred.",
      },
      {
        word: "comp",
        pronunciation: "/kɒmp/",
        definitionEn: "To provide something to a guest free of charge as a gesture of goodwill",
        definitionEs: "Proporcionar algo a un huésped sin cargo como gesto de buena voluntad",
        example: "We comped the dessert after the long wait time.",
      },
      {
        word: "de-escalation",
        pronunciation: "/diː ˌɛskəˈleɪʃən/",
        definitionEn: "The process of reducing a guest's anger or frustration through calm, empathetic communication",
        definitionEs: "El proceso de reducir la ira o frustración de un huésped mediante una comunicación tranquila y empática",
        example: "The manager's de-escalation skills prevented a minor complaint from becoming a public scene.",
      },
    ],
    culturalNote: "In US hospitality, the guest complaint is an opportunity, not a problem. Empowerment — giving front-line staff authority to resolve issues without manager approval — is a key cultural value at premium hotel brands.",
    culturalNoteEs: "En la hospitalidad de EE.UU., la queja del huésped es una oportunidad, no un problema. El empoderamiento — dar al personal de primera línea autoridad para resolver problemas sin aprobación del gerente — es un valor cultural clave en las marcas hoteleras premium.",
  },
  {
    id: "manufacturing-adv-kaizen",
    industry: "manufacturing",
    level: "advanced",
    title: "Leading a Kaizen Event",
    titleEs: "Liderar un Evento Kaizen",
    lines: [
      {
        speaker: "Continuous Improvement Lead",
        role: "Continuous Improvement Lead",
        roleEs: "Líder de Mejora Continua",
        text: "Welcome to the kickoff of our three-day kaizen event on the assembly cell 7 workflow. Our current cycle time is 4.2 minutes per unit and we're targeting 3.5. I want everyone to observe the process with fresh eyes — no assumptions.",
        textEs: "Bienvenidos al inicio de nuestro evento kaizen de tres días sobre el flujo de trabajo de la celda de ensamblaje 7. Nuestro tiempo de ciclo actual es de 4.2 minutos por unidad y apuntamos a 3.5. Quiero que todos observen el proceso con ojos nuevos — sin suposiciones.",
        tip: "'Kaizen' = Japanese for 'continuous improvement' — a structured process to eliminate waste. 'Cycle time' = time to complete one unit. These are core Lean manufacturing terms.",
        tipEs: "'Kaizen' = japonés para 'mejora continua' — un proceso estructurado para eliminar desperdicios. 'Cycle time' = tiempo para completar una unidad. Estos son términos centrales de manufactura Lean.",
      },
      {
        speaker: "Line Operator",
        role: "Assembly Line Operator",
        roleEs: "Operador de Línea de Ensamblaje",
        text: "I've been on this line for four years. The biggest bottleneck I see is the torque verification step — we walk to a shared station every cycle. If we had a dedicated torque wrench at each station, we could cut 30 seconds per unit.",
        textEs: "Llevo cuatro años en esta línea. El mayor cuello de botella que veo es el paso de verificación de torque — caminamos a una estación compartida en cada ciclo. Si tuviéramos una llave de torque dedicada en cada estación, podríamos reducir 30 segundos por unidad.",
        tip: "'Bottleneck' = the step that slows the entire process. The operator's insight is gold in kaizen — frontline workers know the work best. Always engage them first.",
        tipEs: "'Bottleneck' = el paso que ralentiza todo el proceso. La perspectiva del operador es oro en kaizen — los trabajadores de primera línea conocen mejor el trabajo. Siempre involúcrelos primero.",
      },
      {
        speaker: "Continuous Improvement Lead",
        role: "Continuous Improvement Lead",
        roleEs: "Líder de Mejora Continua",
        text: "That's exactly the kind of observation we need. Let's map it on the value stream — I'll mark it as a motion waste. Can we also time-study the current walk distance? We need data before we propose capital expenditure.",
        textEs: "Ese es exactamente el tipo de observación que necesitamos. Mapémoslo en el flujo de valor — lo marcaré como un desperdicio de movimiento. ¿También podemos hacer un estudio de tiempo de la distancia de caminata actual? Necesitamos datos antes de proponer gastos de capital.",
        tip: "'Value stream mapping' = a Lean tool to visualize process flow and identify waste. 'Motion waste' = one of the 8 lean wastes. 'Time-study' = timing each step to find improvement opportunities.",
        tipEs: "'Value stream mapping' = una herramienta Lean para visualizar el flujo del proceso e identificar desperdicios. 'Motion waste' = uno de los 8 desperdicios lean. 'Time-study' = cronometrar cada paso para encontrar oportunidades de mejora.",
      },
      {
        speaker: "Engineer",
        role: "Process Engineer",
        roleEs: "Ingeniero de Procesos",
        text: "I ran a quick time-study this morning — the walk adds 28 seconds per cycle. At our production volume, that's 18 lost hours per week. A dedicated torque wrench is $240 per station — the ROI is less than two weeks.",
        textEs: "Realicé un estudio de tiempo rápido esta mañana — la caminata agrega 28 segundos por ciclo. A nuestro volumen de producción, eso son 18 horas perdidas por semana. Una llave de torque dedicada cuesta $240 por estación — el ROI es menos de dos semanas.",
        tip: "Quantifying waste in hours and dollars (ROI calculation) is how engineers justify improvements in US manufacturing. Data-driven proposals are far more persuasive than opinions.",
        tipEs: "Cuantificar el desperdicio en horas y dólares (cálculo de ROI) es como los ingenieros justifican las mejoras en la manufactura de EE.UU. Las propuestas basadas en datos son mucho más persuasivas que las opiniones.",
      },
    ],
    vocabulary: [
      {
        word: "kaizen",
        pronunciation: "/ˈkaɪzɛn/",
        definitionEn: "A Japanese philosophy of continuous, incremental improvement involving all employees",
        definitionEs: "Una filosofía japonesa de mejora continua e incremental que involucra a todos los empleados",
        example: "The kaizen event reduced setup time by 40% in just three days.",
      },
      {
        word: "value stream mapping",
        pronunciation: "/ˈvæljuː striːm ˈmæpɪŋ/",
        definitionEn: "A Lean tool that visualizes every step in a process to identify waste and improve flow",
        definitionEs: "Una herramienta Lean que visualiza cada paso en un proceso para identificar desperdicios y mejorar el flujo",
        example: "Value stream mapping revealed three unnecessary handoffs in the order fulfillment process.",
      },
      {
        word: "cycle time",
        pronunciation: "/ˈsaɪkəl taɪm/",
        definitionEn: "The total time from the beginning to the end of producing one unit",
        definitionEs: "El tiempo total desde el inicio hasta el fin de producir una unidad",
        example: "Reducing cycle time from 5 to 3.5 minutes increased daily output by 30%.",
      },
    ],
    culturalNote: "In US Lean manufacturing, kaizen events are team-driven, time-boxed improvement sprints. Frontline workers are expected to contribute ideas — their voice is valued as much as engineers'. Data, not hierarchy, drives decisions.",
    culturalNoteEs: "En la manufactura Lean de EE.UU., los eventos kaizen son sprints de mejora impulsados por el equipo y con tiempo limitado. Se espera que los trabajadores de primera línea contribuyan con ideas — su voz se valora tanto como la de los ingenieros. Los datos, no la jerarquía, impulsan las decisiones.",
  },
];
