import type { Industry } from "./content";

export interface QuizQuestion {
  id: string;
  type: "multiple-choice" | "fill-blank" | "translate" | "situation";
  question: string;
  questionEs: string;
  options: string[];
  optionsEs: string[];
  correct: number;
  explanation: string;
  explanationEs: string;
  skill: "vocabulary" | "grammar" | "comprehension" | "cultural" | "speaking";
}

export interface IndustryQuiz {
  industry: Industry;
  title: string;
  titleEs: string;
  description: string;
  descriptionEs: string;
  passingScore: number; // percentage, e.g. 70
  questions: QuizQuestion[];
}

export const QUIZZES: IndustryQuiz[] = [
  // ─── HEALTHCARE ──────────────────────────────────────────────────────────
  {
    industry: "healthcare",
    title: "Healthcare English — Industry Quiz",
    titleEs: "Inglés para la Salud — Quiz de Industria",
    description: "Test your command of professional healthcare English: patient interactions, clinical handoffs, documentation, and workplace culture.",
    descriptionEs: "Pon a prueba tu dominio del inglés profesional para la salud: interacciones con pacientes, traspasos clínicos, documentación y cultura laboral.",
    passingScore: 70,
    questions: [
      {
        id: "hc-q1", type: "multiple-choice", skill: "vocabulary",
        question: "A patient says they are allergic to penicillin. What is the correct professional term for this situation?",
        questionEs: "Un paciente dice ser alérgico a la penicilina. ¿Cuál es el término profesional correcto para esta situación?",
        options: ["A medication preference", "A contraindication", "A side effect", "A prescription note"],
        optionsEs: ["Una preferencia de medicamento", "Una contraindicación", "Un efecto secundario", "Una nota de prescripción"],
        correct: 1,
        explanation: "'Contraindication' means a condition that makes a specific treatment inadvisable. Penicillin allergy is a contraindication to prescribing it.",
        explanationEs: "'Contraindication' significa una condición que hace inadvisable un tratamiento específico. La alergia a la penicilina es una contraindicación para recetarla.",
      },
      {
        id: "hc-q2", type: "situation", skill: "cultural",
        question: "A patient refuses a recommended procedure. What is the correct US healthcare protocol?",
        questionEs: "Un paciente rechaza un procedimiento recomendado. ¿Cuál es el protocolo correcto de salud en EE.UU.?",
        options: ["Call security to enforce the procedure", "Document an AMA (Against Medical Advice) refusal and notify the physician", "Simply cancel the procedure with no documentation", "Ask the patient's family to decide instead"],
        optionsEs: ["Llamar seguridad para forzar el procedimiento", "Documentar un rechazo AMA (Contra el Consejo Médico) y notificar al médico", "Simplemente cancelar el procedimiento sin documentación", "Pedir a la familia del paciente que decida en su lugar"],
        correct: 1,
        explanation: "In the US, patient autonomy is a legal right. The nurse documents the refusal on an AMA form, ensures the patient understands the risks, and notifies the physician.",
        explanationEs: "En EE.UU., la autonomía del paciente es un derecho legal. La enfermera documenta el rechazo en un formulario AMA, asegura que el paciente entienda los riesgos y notifica al médico.",
      },
      {
        id: "hc-q3", type: "multiple-choice", skill: "vocabulary",
        question: "During a nurse shift handoff, you say: 'The patient's ______ is stable at 72 BPM.' What word completes this?",
        questionEs: "Durante un traspaso de turno, dices: 'El ______ del paciente está estable a 72 LPM.' ¿Qué palabra completa esto?",
        options: ["temperature", "heart rate", "blood pressure", "oxygen level"],
        optionsEs: ["temperatura", "frecuencia cardíaca", "presión arterial", "nivel de oxígeno"],
        correct: 1,
        explanation: "BPM = beats per minute. 'Heart rate' is measured in BPM. Normal resting heart rate is 60–100 BPM.",
        explanationEs: "LPM = latidos por minuto. La 'frecuencia cardíaca' se mide en LPM. La frecuencia cardíaca normal en reposo es de 60–100 LPM.",
      },
      {
        id: "hc-q4", type: "translate", skill: "comprehension",
        question: "What does 'the patient is NPO' mean in a clinical setting?",
        questionEs: "¿Qué significa 'the patient is NPO' en un entorno clínico?",
        options: ["The patient needs psychiatric observation", "The patient is not a primary care patient", "The patient must not eat or drink anything", "The patient has no known allergies"],
        optionsEs: ["El paciente necesita observación psiquiátrica", "El paciente no es un paciente de atención primaria", "El paciente no debe comer ni beber nada", "El paciente no tiene alergias conocidas"],
        correct: 2,
        explanation: "NPO comes from the Latin 'nil per os' meaning 'nothing by mouth.' Patients are placed NPO before surgeries or certain procedures.",
        explanationEs: "NPO viene del latín 'nil per os' que significa 'nada por la boca'. Los pacientes se ponen en NPO antes de cirugías o ciertos procedimientos.",
      },
      {
        id: "hc-q5", type: "situation", skill: "cultural",
        question: "A physician says 'I'll give you a heads-up when I'm done with rounds.' What does this mean?",
        questionEs: "Un médico dice 'I'll give you a heads-up when I'm done with rounds.' ¿Qué significa esto?",
        options: ["The physician will literally lift their head", "The physician will give advance notice before finishing rounds", "The physician will skip rounds today", "The physician wants a summary now"],
        optionsEs: ["El médico levantará literalmente la cabeza", "El médico dará aviso previo antes de terminar las rondas", "El médico omitirá las rondas hoy", "El médico quiere un resumen ahora"],
        correct: 1,
        explanation: "'Give a heads-up' is a common US idiom meaning to give someone advance notice or a warning. It's widely used in clinical settings.",
        explanationEs: "'Give a heads-up' es un modismo común en EE.UU. que significa dar aviso previo a alguien. Se usa ampliamente en entornos clínicos.",
      },
      {
        id: "hc-q6", type: "multiple-choice", skill: "grammar",
        question: "Which phrasing is most professional when asking a patient about pain?",
        questionEs: "¿Qué frase es más profesional al preguntar a un paciente sobre el dolor?",
        options: ["Where it hurt?", "Can you describe your pain and rate it from 1 to 10?", "You have pain, yes?", "Pain is bad?"],
        optionsEs: ["¿Dónde duele?", "¿Puede describir su dolor y calificarlo del 1 al 10?", "¿Usted tiene dolor, sí?", "¿El dolor es malo?"],
        correct: 1,
        explanation: "Professional clinical communication uses complete, open-ended questions. Rating scales (1–10) are standard in US pain assessment.",
        explanationEs: "La comunicación clínica profesional usa preguntas completas y abiertas. Las escalas de calificación (1–10) son estándar en la evaluación de dolor en EE.UU.",
      },
      {
        id: "hc-q7", type: "translate", skill: "vocabulary",
        question: "What does 'disposition' mean in the context of hospital discharge planning?",
        questionEs: "¿Qué significa 'disposition' en el contexto de la planificación del alta hospitalaria?",
        options: ["A patient's personality type", "The plan for where a patient goes after leaving the hospital", "A medication dosage schedule", "A type of surgical procedure"],
        optionsEs: ["El tipo de personalidad del paciente", "El plan de a dónde va el paciente al salir del hospital", "Un calendario de dosis de medicamento", "Un tipo de procedimiento quirúrgico"],
        correct: 1,
        explanation: "In discharge planning, 'disposition' refers to the patient's next destination — home, skilled nursing facility, rehabilitation, etc.",
        explanationEs: "En la planificación del alta, 'disposition' se refiere al próximo destino del paciente — hogar, centro de enfermería especializada, rehabilitación, etc.",
      },
      {
        id: "hc-q8", type: "situation", skill: "comprehension",
        question: "Your supervisor says: 'Please follow up on the pending lab results for Room 8.' What should you do?",
        questionEs: "Tu supervisor dice: 'Please follow up on the pending lab results for Room 8.' ¿Qué debes hacer?",
        options: ["Order new lab tests for Room 8", "Check whether the expected lab results have arrived and take action", "Move the patient in Room 8 to another floor", "Ignore it until the end of shift"],
        optionsEs: ["Ordenar nuevas pruebas de laboratorio para el Cuarto 8", "Verificar si los resultados de laboratorio esperados han llegado y tomar acción", "Mover al paciente del Cuarto 8 a otro piso", "Ignorarlo hasta el final del turno"],
        correct: 1,
        explanation: "'Follow up' means to check on something and ensure it is completed. Pending = not yet received. This is a direct task assignment.",
        explanationEs: "'Follow up' significa verificar algo y asegurar que esté completo. Pending = aún no recibido. Esta es una asignación de tarea directa.",
      },
    ],
  },

  // ─── CONSTRUCTION ─────────────────────────────────────────────────────────
  {
    industry: "construction",
    title: "Construction English — Industry Quiz",
    titleEs: "Inglés para la Construcción — Quiz de Industria",
    description: "Demonstrate your mastery of job-site safety language, contract terms, change orders, and professional trade communication.",
    descriptionEs: "Demuestra tu dominio del lenguaje de seguridad en obra, términos contractuales, órdenes de cambio y comunicación profesional de oficios.",
    passingScore: 70,
    questions: [
      {
        id: "cn-q1", type: "multiple-choice", skill: "vocabulary",
        question: "On a US job site, 'PPE' stands for what?",
        questionEs: "En una obra en EE.UU., 'PPE' significa ¿qué?",
        options: ["Project Planning and Execution", "Personal Protective Equipment", "Pre-Pour Evaluation", "Primary Project Engineer"],
        optionsEs: ["Planificación y Ejecución del Proyecto", "Equipo de Protección Personal", "Evaluación Pre-Vaciado", "Ingeniero Principal del Proyecto"],
        correct: 1,
        explanation: "PPE = Personal Protective Equipment. It includes hard hats, safety glasses, gloves, steel-toed boots, and harnesses. Required by OSHA on all US job sites.",
        explanationEs: "PPE = Equipo de Protección Personal. Incluye cascos, lentes de seguridad, guantes, botas con puntera de acero y arneses. Requerido por OSHA en todas las obras de EE.UU.",
      },
      {
        id: "cn-q2", type: "situation", skill: "cultural",
        question: "You notice the architectural drawings don't match the field conditions. What is the correct professional action?",
        questionEs: "Notas que los planos arquitectónicos no coinciden con las condiciones en campo. ¿Cuál es la acción profesional correcta?",
        options: ["Proceed with construction using your best judgment", "Stop work and submit an RFI (Request for Information) to the architect", "Fix the drawings yourself", "Tell the owner to hire a better architect"],
        optionsEs: ["Continuar con la construcción usando tu mejor juicio", "Parar el trabajo y enviar un RFI (Solicitud de Información) al arquitecto", "Corregir los planos tú mismo", "Decirle al propietario que contrate a un mejor arquitecto"],
        correct: 1,
        explanation: "An RFI (Request for Information) is the formal process for flagging drawing discrepancies. Never proceed on a discrepancy without written authorization — it protects everyone.",
        explanationEs: "Un RFI (Solicitud de Información) es el proceso formal para señalar discrepancias en los planos. Nunca avances con una discrepancia sin autorización escrita — protege a todos.",
      },
      {
        id: "cn-q3", type: "multiple-choice", skill: "vocabulary",
        question: "A subcontractor requests a 'change order.' What does this mean?",
        questionEs: "Un subcontratista solicita una 'change order.' ¿Qué significa esto?",
        options: ["A request to change the project team", "A formal contract modification for added scope or cost", "An order to change the construction schedule", "A permit application"],
        optionsEs: ["Una solicitud para cambiar el equipo del proyecto", "Una modificación formal del contrato por alcance o costo adicional", "Una orden para cambiar el cronograma de construcción", "Una solicitud de permiso"],
        correct: 1,
        explanation: "A change order (CO) is a formal written amendment to the contract that documents scope changes and their cost/schedule impact. Both parties must sign it.",
        explanationEs: "Una orden de cambio (CO) es una enmienda escrita formal al contrato que documenta los cambios de alcance y su impacto en costo/cronograma. Ambas partes deben firmarla.",
      },
      {
        id: "cn-q4", type: "translate", skill: "comprehension",
        question: "The foreman says: 'We're doing a pre-pour inspection at 7 AM.' What is about to happen?",
        questionEs: "El capataz dice: 'We're doing a pre-pour inspection at 7 AM.' ¿Qué está a punto de pasar?",
        options: ["Workers will pour concrete at 7 AM", "An inspection will happen before concrete is poured", "The shift starts at 7 AM", "A safety meeting will be held at 7 AM"],
        optionsEs: ["Los trabajadores vaciarán concreto a las 7 AM", "Se realizará una inspección antes de vaciar el concreto", "El turno empieza a las 7 AM", "Se realizará una reunión de seguridad a las 7 AM"],
        correct: 1,
        explanation: "'Pre-pour' = before the concrete pour. An inspector checks the formwork, rebar, and grade before any concrete is placed.",
        explanationEs: "'Pre-pour' = antes del vaciado de concreto. Un inspector verifica la formaleta, el acero de refuerzo y el nivel antes de colocar cualquier concreto.",
      },
      {
        id: "cn-q5", type: "situation", skill: "cultural",
        question: "A city inspector fails two items on your framing inspection. What is the best response?",
        questionEs: "Un inspector municipal reprueba dos elementos en tu inspección de enmarcado. ¿Cuál es la mejor respuesta?",
        options: ["Argue that the inspector is wrong", "Thank the inspector, ask for the code reference, commit to a correction timeline, and request a re-inspection", "Ignore the failed items and proceed", "Call the building department to complain"],
        optionsEs: ["Argumentar que el inspector está equivocado", "Agradecer al inspector, pedir la referencia del código, comprometerse a un plazo de corrección y solicitar una re-inspección", "Ignorar los elementos reprobados y continuar", "Llamar al departamento de construcción para quejarse"],
        correct: 1,
        explanation: "In US construction, inspectors have authority. Professional response = accept the correction notice professionally, understand exactly what needs fixing, fix it, and schedule a re-inspection.",
        explanationEs: "En construcción en EE.UU., los inspectores tienen autoridad. La respuesta profesional = aceptar el aviso de corrección profesionalmente, entender exactamente qué necesita corregirse, corregirlo y programar una re-inspección.",
      },
      {
        id: "cn-q6", type: "multiple-choice", skill: "vocabulary",
        question: "What does 'scope creep' mean on a construction project?",
        questionEs: "¿Qué significa 'scope creep' en un proyecto de construcción?",
        options: ["A slow leak in the project budget", "Extra work added without a formal change order", "Workers arriving late each day", "A gradual increase in material costs"],
        optionsEs: ["Una fuga lenta en el presupuesto del proyecto", "Trabajo extra añadido sin una orden de cambio formal", "Trabajadores llegando tarde cada día", "Un aumento gradual en los costos de materiales"],
        correct: 1,
        explanation: "Scope creep = work that grows beyond the original contract without a formal change order. It leads to unpaid labor and disputes. Always document additions in writing.",
        explanationEs: "Scope creep = trabajo que crece más allá del contrato original sin una orden de cambio formal. Lleva a trabajo no pagado y disputas. Siempre documenta las adiciones por escrito.",
      },
      {
        id: "cn-q7", type: "situation", skill: "grammar",
        question: "Which sentence correctly reports a safety hazard to your supervisor?",
        questionEs: "¿Qué oración reporta correctamente un peligro de seguridad a tu supervisor?",
        options: ["There is problem with the scaffold.", "I need to flag a safety issue — the scaffold on Level 3 has a missing guardrail.", "Scaffold bad on Level 3.", "Maybe the scaffold is not good?"],
        optionsEs: ["Hay problema con el andamio.", "Necesito señalar un problema de seguridad — el andamio en el Nivel 3 tiene una baranda faltante.", "Andamio malo en Nivel 3.", "¿Quizás el andamio no está bien?"],
        correct: 1,
        explanation: "'Flag a safety issue' is the professional phrase. Always be specific: name the location and the exact problem. This enables fast, accurate action.",
        explanationEs: "'Flag a safety issue' es la frase profesional. Siempre sé específico: nombra la ubicación y el problema exacto. Esto permite una acción rápida y precisa.",
      },
      {
        id: "cn-q8", type: "multiple-choice", skill: "cultural",
        question: "On a US job site, 'OSHA' refers to what?",
        questionEs: "En una obra de EE.UU., 'OSHA' se refiere a ¿qué?",
        options: ["The project owner's safety handbook", "Occupational Safety and Health Administration — the federal workplace safety agency", "A type of construction permit", "The site foreman's certification"],
        optionsEs: ["El manual de seguridad del propietario del proyecto", "Administración de Seguridad y Salud Ocupacional — la agencia federal de seguridad laboral", "Un tipo de permiso de construcción", "La certificación del capataz de obra"],
        correct: 1,
        explanation: "OSHA (Occupational Safety and Health Administration) sets and enforces federal workplace safety standards. OSHA violations can result in fines and project shutdowns.",
        explanationEs: "OSHA (Administración de Seguridad y Salud Ocupacional) establece y hace cumplir los estándares federales de seguridad laboral. Las violaciones de OSHA pueden resultar en multas y cierre del proyecto.",
      },
    ],
  },

  // ─── RESTAURANT ───────────────────────────────────────────────────────────
  {
    industry: "restaurant",
    title: "Restaurant English — Industry Quiz",
    titleEs: "Inglés para Restaurantes — Quiz de Industria",
    description: "Test your knowledge of front-of-house service language, kitchen communication, and US hospitality culture.",
    descriptionEs: "Pon a prueba tu conocimiento del lenguaje de servicio, comunicación de cocina y cultura de hostelería en EE.UU.",
    passingScore: 70,
    questions: [
      { id:"rs-q1", type:"multiple-choice", skill:"vocabulary", question:"A kitchen manager says 'We're 86 on the lobster bisque.' What does this mean?", questionEs:"El gerente dice 'We're 86 on the lobster bisque.' ¿Qué significa?", options:["86 portions remain","It's sold out and unavailable","It will be ready in 86 minutes","Table 86 ordered it"], optionsEs:["Quedan 86 porciones","Está agotado y no disponible","Estará listo en 86 minutos","La mesa 86 lo ordenó"], correct:1, explanation:"'86' is universal US restaurant slang meaning an item is no longer available.", explanationEs:"'86' es jerga de restaurantes en EE.UU. que significa que un artículo ya no está disponible." },
      { id:"rs-q2", type:"situation", skill:"cultural", question:"A customer complains their steak is overcooked. What is the correct response?", questionEs:"Un cliente se queja de que su bistec está demasiado cocido. ¿Cuál es la respuesta correcta?", options:["Tell them they ordered wrong","Apologize sincerely, take the plate back, and offer a remake","Offer a 10% discount only","Ignore it"], optionsEs:["Decirle que ordenó mal","Disculparse, retirar el plato y ofrecer rehacer","Solo ofrecer 10% de descuento","Ignorarlo"], correct:1, explanation:"A sincere apology + a concrete fix is the US standard. Never blame the guest.", explanationEs:"Una disculpa sincera + una solución concreta es el estándar en EE.UU. Nunca culpes al cliente." },
      { id:"rs-q3", type:"multiple-choice", skill:"vocabulary", question:"What does 'mise en place' mean in a professional kitchen?", questionEs:"¿Qué significa 'mise en place' en una cocina profesional?", options:["Daily menu specials","Health code cleanliness standard","Everything in its place — prep completed before service","Hand-washing procedure"], optionsEs:["Especiales del menú del día","Estándar de limpieza del código de salud","Todo en su lugar — preparación completa antes del servicio","Procedimiento de lavado de manos"], correct:2, explanation:"'Mise en place' means having all ingredients prepped and organized before service begins.", explanationEs:"'Mise en place' significa tener todos los ingredientes preparados y organizados antes de que comience el servicio." },
      { id:"rs-q4", type:"translate", skill:"comprehension", question:"A server says: 'Can I start you off with something to drink?' What is the server doing?", questionEs:"Un mesero dice: 'Can I start you off with something to drink?' ¿Qué está haciendo?", options:["Explaining the kitchen isn't ready","Offering a beverage before taking the food order","Asking if they're ready to pay","Explaining menu specials"], optionsEs:["Explicando que la cocina no está lista","Ofreciendo una bebida antes de tomar el pedido","Preguntando si están listos para pagar","Explicando especiales del menú"], correct:1, explanation:"'Start you off' is professional phrasing meaning 'begin your experience with.' Taking drink orders first is standard US service sequence.", explanationEs:"'Start you off' es frase profesional que significa 'comenzar tu experiencia con'. Tomar pedidos de bebida primero es secuencia de servicio estándar en EE.UU." },
      { id:"rs-q5", type:"situation", skill:"cultural", question:"A guest has a severe peanut allergy. You are the server. What do you do?", questionEs:"Un huésped tiene alergia grave a los cacahuates. Eres el mesero. ¿Qué haces?", options:["Note it mentally","Immediately inform the kitchen and put an allergy alert on the ticket","Tell the guest to order something without peanuts","Ask the manager if it matters"], optionsEs:["Anotarlo mentalmente","Informar inmediatamente a la cocina y poner alerta de alergia en el ticket","Decirle que ordene algo sin cacahuates","Preguntarle al gerente si importa"], correct:1, explanation:"Severe allergies are life-threatening. US restaurants require written allergy alerts on every ticket.", explanationEs:"Las alergias graves pueden ser mortales. Los restaurantes de EE.UU. requieren alertas escritas en cada ticket." },
      { id:"rs-q6", type:"multiple-choice", skill:"vocabulary", question:"What is the correct term for food packaged for a customer to take home?", questionEs:"¿Cuál es el término correcto para comida empacada para llevar?", options:["Carry-out or to-go order","Walk-away food","Departure meal","Exit order"], optionsEs:["Pedido para llevar (to-go)","Comida para caminar","Comida de salida","Orden de salida"], correct:0, explanation:"'To-go' and 'carry-out' are the standard US terms. 'For here or to go?' is one of the most common server questions.", explanationEs:"'To-go' y 'carry-out' son los términos estándar en EE.UU. '¿Para aquí o para llevar?' es una de las preguntas más comunes." },
      { id:"rs-q7", type:"situation", skill:"grammar", question:"Which sentence correctly takes a customer modification request?", questionEs:"¿Qué oración toma correctamente una solicitud de modificación?", options:["No onion possible?","Can I get that without onions, please?","I don't want onion on it.","Remove onion!"], optionsEs:["¿Sin cebolla posible?","¿Me lo puede traer sin cebolla, por favor?","No quiero cebolla en eso.","¡Quita la cebolla!"], correct:1, explanation:"'Can I get that without...?' is the natural, polite US phrasing for modifying an order.", explanationEs:"'Can I get that without...?' es la forma natural y cortés en EE.UU. para modificar un pedido." },
      { id:"rs-q8", type:"multiple-choice", skill:"cultural", question:"In US restaurants, what is the expected tip percentage for good service?", questionEs:"En restaurantes de EE.UU., ¿cuál es el porcentaje de propina esperado por buen servicio?", options:["5–8%","10–12%","15–20%","25–30%"], optionsEs:["5–8%","10–12%","15–20%","25–30%"], correct:2, explanation:"15–20% is the standard tipping range for good service. Tipping is not optional — servers depend on it.", explanationEs:"15–20% es el rango de propina estándar. La propina no es opcional — los meseros dependen de ella." },
    ],
  },

  // ─── OFFICE ───────────────────────────────────────────────────────────────
  {
    industry: "office",
    title: "Office & Admin English — Industry Quiz",
    titleEs: "Inglés para Oficina — Quiz de Industria",
    description: "Test your command of professional office communication: meetings, emails, feedback, and workplace norms.",
    descriptionEs: "Pon a prueba tu dominio de la comunicación profesional de oficina: reuniones, correos, retroalimentación y normas laborales.",
    passingScore: 70,
    questions: [
      { id:"of-q1", type:"multiple-choice", skill:"vocabulary", question:"In a meeting, 'action items' refers to what?", questionEs:"En una reunión, 'action items' se refiere a ¿qué?", options:["Topics for discussion","Tasks assigned that must be completed","Agenda items for next meeting","Notes taken during meeting"], optionsEs:["Temas de discusión","Tareas asignadas que deben completarse","Puntos de agenda para la próxima reunión","Notas tomadas durante la reunión"], correct:1, explanation:"'Action items' are specific tasks with owners and deadlines from a meeting.", explanationEs:"'Action items' son tareas específicas con responsables y fechas límite de una reunión." },
      { id:"of-q2", type:"situation", skill:"cultural", question:"Your manager says: 'Let's circle back on this later.' What does this mean?", questionEs:"Tu gerente dice: 'Let's circle back on this later.' ¿Qué significa?", options:["Return to this topic at a later time","This topic is closed forever","You made a mistake","The meeting is over"], optionsEs:["Volver a este tema más tarde","Este tema está cerrado para siempre","Cometiste un error","La reunión terminó"], correct:0, explanation:"'Circle back' is a very common US office phrase meaning to return to a topic later.", explanationEs:"'Circle back' es una frase muy común en oficinas de EE.UU. que significa volver a un tema más tarde." },
      { id:"of-q3", type:"multiple-choice", skill:"vocabulary", question:"'I don't have the bandwidth for this project.' What does 'bandwidth' mean here?", questionEs:"'I don't have the bandwidth for this project.' ¿Qué significa 'bandwidth' aquí?", options:["Slow internet connection","Not enough time or capacity to take on more work","Not qualified for the project","Going on vacation"], optionsEs:["Conexión a internet lenta","No tiene tiempo ni capacidad para asumir más trabajo","No calificado para el proyecto","De vacaciones"], correct:1, explanation:"In US office culture, 'bandwidth' means available time and capacity. 'No bandwidth' = too busy.", explanationEs:"En la cultura de oficina de EE.UU., 'bandwidth' significa tiempo y capacidad disponible. 'No bandwidth' = demasiado ocupado." },
      { id:"of-q4", type:"translate", skill:"comprehension", question:"An email says: 'Please advise on the timeline for the deliverables.' What is being asked?", questionEs:"Un correo dice: 'Please advise on the timeline for the deliverables.' ¿Qué se pide?", options:["A meeting","Information about when project outputs will be ready","Advice on the team","A performance report"], optionsEs:["Una reunión","Información sobre cuándo estarán listos los entregables","Consejos sobre el equipo","Un informe de desempeño"], correct:1, explanation:"'Please advise' = please provide information. 'Deliverables' = the specific outputs that must be completed.", explanationEs:"'Please advise' = por favor proporcione información. 'Deliverables' = los productos específicos que deben completarse." },
      { id:"of-q5", type:"situation", skill:"grammar", question:"Which email opening is most professional in a US business context?", questionEs:"¿Qué apertura de correo es más profesional en un contexto de negocios en EE.UU.?", options:["Hey!","Dear Sir or Madam,","Hi Sarah, I hope you're doing well.","To Who It May Concern,"], optionsEs:["¡Hola!","Estimado Señor o Señora,","Hola Sarah, espero que estés bien.","A quien corresponda,"], correct:2, explanation:"In modern US business email, 'Hi [First Name],' is standard — professional but approachable.", explanationEs:"En el correo de negocios moderno en EE.UU., 'Hi [Nombre],' es el estándar — profesional pero accesible." },
      { id:"of-q6", type:"multiple-choice", skill:"vocabulary", question:"A manager says: 'Let's take this offline.' What do they mean?", questionEs:"Un gerente dice: 'Let's take this offline.' ¿Qué quieren decir?", options:["Move to a video call","Discuss this separately after the meeting","Cancel the project","Disconnect from the internet"], optionsEs:["Pasar a videollamada","Discutir esto por separado después de la reunión","Cancelar el proyecto","Desconectarse del internet"], correct:1, explanation:"'Take it offline' = discuss separately, after the main meeting. Used when a topic is too detailed for the full group.", explanationEs:"'Take it offline' = discutir por separado, después de la reunión principal. Se usa cuando un tema es demasiado detallado para todo el grupo." },
      { id:"of-q7", type:"situation", skill:"comprehension", question:"Your colleague says: 'I'm going to loop in the legal team on this.' What will happen?", questionEs:"Tu colega dice: 'I'm going to loop in the legal team.' ¿Qué pasará?", options:["Legal handles the project alone","Legal will be included in the communication","A contract will be signed","The project is delayed"], optionsEs:["Legal manejará el proyecto solo","Legal será incluido en la comunicación","Se firmará un contrato","El proyecto se retrasa"], correct:1, explanation:"'Loop in' means to include someone by adding them to an email or meeting.", explanationEs:"'Loop in' significa incluir a alguien añadiéndolo a un correo o reunión." },
      { id:"of-q8", type:"multiple-choice", skill:"cultural", question:"'That's not on my radar yet' means:", questionEs:"'That's not on my radar yet' significa:", options:["No radar device available","Not yet aware of or focused on it","Classified information","Project deleted"], optionsEs:["No hay dispositivo de radar","Aún no consciente de o enfocado en ello","Información clasificada","Proyecto eliminado"], correct:1, explanation:"'On my radar' = aware of / paying attention to. Very common US workplace idiom.", explanationEs:"'On my radar' = consciente de / prestando atención a. Modismo laboral muy común en EE.UU." },
    ],
  },

  // ─── RETAIL ───────────────────────────────────────────────────────────────
  {
    industry: "retail",
    title: "Retail English — Industry Quiz",
    titleEs: "Inglés para Comercio Minorista — Quiz de Industria",
    description: "Test your retail English: customer service, loss prevention, inventory, and US store culture.",
    descriptionEs: "Pon a prueba tu inglés para comercio: servicio al cliente, prevención de pérdidas, inventario y cultura de tiendas en EE.UU.",
    passingScore: 70,
    questions: [
      { id:"rt-q1", type:"multiple-choice", skill:"vocabulary", question:"In retail, 'shrink' refers to what?", questionEs:"En el comercio minorista, 'shrink' se refiere a ¿qué?", options:["Clothing washed too hot","Inventory loss due to theft, damage, or error","Reduction in store hours","A smaller product size"], optionsEs:["Ropa lavada a temperatura alta","Pérdida de inventario por robo, daño o error","Reducción del horario","Un tamaño de producto más pequeño"], correct:1, explanation:"Shrink is inventory loss from shoplifting, employee theft, vendor fraud, or paperwork errors.", explanationEs:"Shrink es pérdida de inventario por robo de clientes, empleados, fraude de proveedores o errores de papeleo." },
      { id:"rt-q2", type:"situation", skill:"cultural", question:"A customer wants to return an item without a receipt. What is the professional response?", questionEs:"Un cliente quiere devolver un artículo sin recibo. ¿Cuál es la respuesta profesional?", options:["Refuse immediately","Explain the return policy and offer available options","Accept without question","Ask them to leave"], optionsEs:["Rechazar de inmediato","Explicar la política de devolución y ofrecer opciones disponibles","Aceptar sin cuestionamiento","Pedirles que se vayan"], correct:1, explanation:"US retail best practice: explain the policy, offer alternatives (store credit, exchange), and maintain a helpful tone.", explanationEs:"Mejor práctica en EE.UU.: explica la política, ofrece alternativas (crédito en tienda, cambio) y mantén un tono útil." },
      { id:"rt-q3", type:"translate", skill:"vocabulary", question:"The manager says: 'Make sure we have full coverage on the floor.' What does this mean?", questionEs:"El gerente dice: 'Make sure we have full coverage on the floor.' ¿Qué significa?", options:["Cover shelves with a tarp","All sales floor areas must have staff assigned","The floor needs mopping","All merchandise needs price tags"], optionsEs:["Cubrir estantes con una lona","Todas las áreas del piso de ventas deben tener personal","El piso necesita trapearse","Toda la mercancía necesita etiquetas"], correct:1, explanation:"'Coverage on the floor' means having enough staff on the sales floor to assist customers.", explanationEs:"'Coverage on the floor' significa tener suficiente personal en el piso de ventas para atender a los clientes." },
      { id:"rt-q4", type:"multiple-choice", skill:"vocabulary", question:"What is 'ATV' in retail reporting?", questionEs:"¿Qué es 'ATV' en informes de comercio?", options:["Automated Track Vehicle","All-Terrain Vehicle","Average Transaction Value","Annual Total Volume"], optionsEs:["Vehículo de pista automatizado","Vehículo todo terreno","Valor Promedio de Transacción","Volumen Total Anual"], correct:2, explanation:"ATV = Average Transaction Value — the average dollar amount per purchase.", explanationEs:"ATV = Valor Promedio de Transacción — el monto promedio en dólares por compra." },
      { id:"rt-q5", type:"situation", skill:"grammar", question:"A customer seems frustrated while browsing. Which approach is best?", questionEs:"Un cliente parece frustrado mientras busca. ¿Cuál es el mejor enfoque?", options:["Wait for them to ask","Say: 'Are you finding everything okay today? I'm happy to help.'","Say: 'You need help or what?'","Follow them silently"], optionsEs:["Esperar a que pidan ayuda","Decir: '¿Está encontrando todo bien hoy? Con gusto le ayudo.'","Decir: '¿Necesita ayuda o qué?'","Seguirlos en silencio"], correct:1, explanation:"'Are you finding everything okay?' is the standard US retail greeting for customers already browsing.", explanationEs:"'Are you finding everything okay?' es el saludo estándar en EE.UU. para clientes que ya están buscando." },
      { id:"rt-q6", type:"multiple-choice", skill:"vocabulary", question:"What does 'stock the floor' mean?", questionEs:"¿Qué significa 'stock the floor'?", options:["Buy shares","Move inventory from stockroom to sales floor shelves","Count all items","Mop the floor"], optionsEs:["Comprar acciones","Mover inventario de la bodega a los estantes del piso de ventas","Contar todos los artículos","Trapear el piso"], correct:1, explanation:"'Stock the floor' = replenish sales floor shelves with inventory from the back stockroom.", explanationEs:"'Stock the floor' = reabastecer los estantes del piso de ventas con inventario de la bodega." },
      { id:"rt-q7", type:"translate", skill:"comprehension", question:"A notice says: 'Confirm receipt of this policy by signing the sheet at the host stand.' What must you do?", questionEs:"Un aviso dice: 'Confirm receipt of this policy by signing the sheet at the host stand.' ¿Qué debes hacer?", options:["Email policy to manager","Sign a paper at the host stand to acknowledge receipt","Read aloud to team","Fill out an online form"], optionsEs:["Enviar política por correo al gerente","Firmar un papel en el mostrador para confirmar recepción","Leer en voz alta al equipo","Llenar un formulario en línea"], correct:1, explanation:"'Confirm receipt' = acknowledge you received and read the document. 'Sign the sheet' is the physical confirmation.", explanationEs:"'Confirm receipt' = reconocer que recibiste y leíste el documento. 'Sign the sheet' es la confirmación física." },
      { id:"rt-q8", type:"multiple-choice", skill:"cultural", question:"In US retail, what is the standard customer greeting time target?", questionEs:"En el comercio de EE.UU., ¿cuál es el objetivo estándar de tiempo de saludo?", options:["Within 5 minutes","Within 30–60 seconds","Only when asked","Only at checkout"], optionsEs:["En menos de 5 minutos","En menos de 30–60 segundos","Solo cuando se pide","Solo en el pago"], correct:1, explanation:"Most US retailers set a 30–90 second greeting standard. Acknowledged customers are less likely to shoplift.", explanationEs:"La mayoría de los minoristas de EE.UU. establecen un estándar de saludo de 30–90 segundos. Los clientes saludados tienen menos probabilidad de robar." },
    ],
  },

  // ─── TECHNOLOGY ───────────────────────────────────────────────────────────
  {
    industry: "technology",
    title: "Technology English — Industry Quiz",
    titleEs: "Inglés para Tecnología — Quiz de Industria",
    description: "Test your command of tech workplace vocabulary, agile processes, incident communication, and US software culture.",
    descriptionEs: "Pon a prueba tu dominio del vocabulario tecnológico, procesos ágiles, comunicación de incidentes y cultura de software en EE.UU.",
    passingScore: 70,
    questions: [
      { id:"tc-q1", type:"multiple-choice", skill:"vocabulary", question:"In a daily standup, what is a 'blocker'?", questionEs:"En un standup diario, ¿qué es un 'blocker'?", options:["A senior developer","An obstacle preventing progress on a task","A code review comment","A type of database query"], optionsEs:["Un desarrollador senior","Un obstáculo que impide el progreso en una tarea","Un comentario de revisión de código","Un tipo de consulta de base de datos"], correct:1, explanation:"A blocker is anything preventing you from completing your work. Always flag blockers immediately in the standup so they can be resolved.", explanationEs:"Un blocker es cualquier cosa que te impide completar tu trabajo. Siempre señala los blockers de inmediato en el standup para que puedan resolverse." },
      { id:"tc-q2", type:"translate", skill:"comprehension", question:"A manager says: 'We need to deploy the hotfix before end of day.' What must happen?", questionEs:"Un gerente dice: 'We need to deploy the hotfix before end of day.' ¿Qué debe pasar?", options:["A meeting must be scheduled","The emergency code fix must be released to production today","The server must be restarted","The sprint must be extended"], optionsEs:["Se debe programar una reunión","La corrección de emergencia debe lanzarse a producción hoy","El servidor debe reiniciarse","El sprint debe extenderse"], correct:1, explanation:"'Deploy' = release code to production. 'Hotfix' = an urgent patch for a critical bug. 'Before end of day' = by close of business.", explanationEs:"'Deploy' = lanzar código a producción. 'Hotfix' = un parche urgente para un error crítico. 'Before end of day' = antes del cierre del día laboral." },
      { id:"tc-q3", type:"multiple-choice", skill:"vocabulary", question:"What does it mean when a system returns a '503 Service Unavailable' error?", questionEs:"¿Qué significa cuando un sistema devuelve un error '503 Service Unavailable'?", options:["The user doesn't have permission","The server is temporarily unable to handle requests","The page was not found","The request was successful"], optionsEs:["El usuario no tiene permiso","El servidor no puede manejar solicitudes temporalmente","La página no fue encontrada","La solicitud fue exitosa"], correct:1, explanation:"503 = server temporarily unavailable, usually during maintenance or high load. 404 = not found; 403 = forbidden; 200 = success.", explanationEs:"503 = servidor no disponible temporalmente, generalmente durante mantenimiento o carga alta. 404 = no encontrado; 403 = prohibido; 200 = éxito." },
      { id:"tc-q4", type:"situation", skill:"cultural", question:"During a post-mortem, a colleague asks: 'Who caused the outage?' What is the correct response in a blameless culture?", questionEs:"Durante un post-mortem, un colega pregunta: '¿Quién causó la interrupción?' ¿Cuál es la respuesta correcta en una cultura sin culpa?", options:["Name the person who deployed the code","Redirect: 'Let's focus on system factors and what we can change'","Report the person to HR","Refuse to answer"], optionsEs:["Nombrar a la persona que hizo el deploy","Redirigir: 'Enfoquémonos en los factores del sistema y en lo que podemos cambiar'","Reportar a la persona a RRHH","Negarse a responder"], correct:1, explanation:"Blameless post-mortems focus on system factors, not individuals. The goal is learning and improvement, not punishment.", explanationEs:"Los post-mortems sin culpa se enfocan en factores del sistema, no en individuos. El objetivo es aprender y mejorar, no castigar." },
      { id:"tc-q5", type:"multiple-choice", skill:"vocabulary", question:"What is a 'sprint' in agile software development?", questionEs:"¿Qué es un 'sprint' en el desarrollo de software ágil?", options:["Running a speed test on the server","A short development cycle, usually 1–2 weeks","A type of code review","A user interface prototype"], optionsEs:["Ejecutar una prueba de velocidad en el servidor","Un ciclo corto de desarrollo, generalmente 1–2 semanas","Un tipo de revisión de código","Un prototipo de interfaz de usuario"], correct:1, explanation:"A sprint is a fixed-length iteration (usually 1–2 weeks) where a team completes a set of defined work items from the backlog.", explanationEs:"Un sprint es una iteración de duración fija (generalmente 1–2 semanas) donde un equipo completa un conjunto de elementos de trabajo definidos del backlog." },
      { id:"tc-q6", type:"translate", skill:"comprehension", question:"An email says: 'Please validate the patch in staging before production deployment.' What must happen first?", questionEs:"Un correo dice: 'Please validate the patch in staging before production deployment.' ¿Qué debe pasar primero?", options:["Deploy immediately to production","Test the fix in the staging environment before releasing it live","Send the patch to the client","Document the fix in Jira"], optionsEs:["Desplegar de inmediato a producción","Probar la corrección en el entorno de staging antes de lanzarla en vivo","Enviar el parche al cliente","Documentar la corrección en Jira"], correct:1, explanation:"'Staging' = a test environment that mirrors production. Always validate in staging before deploying live to avoid introducing new issues.", explanationEs:"'Staging' = un entorno de prueba que imita producción. Siempre valida en staging antes de desplegar en vivo para evitar introducir nuevos problemas." },
      { id:"tc-q7", type:"situation", skill:"grammar", question:"Which standup update is most professional and complete?", questionEs:"¿Cuál actualización de standup es más profesional y completa?", options:["I did stuff yesterday, doing more today.","Yesterday I completed the auth fix. Today I'm starting the dashboard API. No blockers.","Working on the same thing.","Nothing to report."], optionsEs:["Hice cosas ayer, haciendo más hoy.","Ayer completé la corrección de autenticación. Hoy empiezo la API del dashboard. Sin blockers.","Trabajando en lo mismo.","Nada que reportar."], correct:1, explanation:"The three-part format: what you did, what you'll do, any blockers. Specific and quantified. This is the gold standard for standup updates.", explanationEs:"El formato de tres partes: qué hiciste, qué harás, algún blocker. Específico y cuantificado. Este es el estándar de oro para actualizaciones de standup." },
      { id:"tc-q8", type:"multiple-choice", skill:"cultural", question:"In a US tech company, 'LGTM' in a code review comment means:", questionEs:"En una empresa de tecnología de EE.UU., 'LGTM' en un comentario de revisión de código significa:", options:["Let's Get To the Meeting","Looks Good To Me — an approval","Let's Generate Test Metrics","Large Group Technical Meeting"], optionsEs:["Vamos a la reunión","Se ve bien para mí — una aprobación","Generemos métricas de prueba","Gran reunión técnica de grupo"], correct:1, explanation:"LGTM = 'Looks Good To Me' — a common shorthand for approving code in a pull request review.", explanationEs:"LGTM = 'Looks Good To Me' (Se ve bien para mí) — abreviatura común para aprobar código en una revisión de pull request." },
    ],
  },

  // ─── LOGISTICS ────────────────────────────────────────────────────────────
  {
    industry: "logistics",
    title: "Logistics English — Industry Quiz",
    titleEs: "Inglés para Logística — Quiz de Industria",
    description: "Test your logistics English: freight terms, documentation, carrier communication, and US supply chain culture.",
    descriptionEs: "Pon a prueba tu inglés para logística: términos de carga, documentación, comunicación con transportistas y cultura de cadena de suministro en EE.UU.",
    passingScore: 70,
    questions: [
      { id:"lg-q1", type:"multiple-choice", skill:"vocabulary", question:"What is a 'BOL' in freight shipping?", questionEs:"¿Qué es un 'BOL' en el envío de carga?", options:["Bill of Lading — a shipping document that is the contract between shipper and carrier","Bill of Labor — a payroll document","Box of Logistics — a container type","Back-Order Log — a record of delayed items"], optionsEs:["Conocimiento de Embarque — un documento de envío que es el contrato entre el remitente y el transportista","Factura de mano de obra — un documento de nómina","Caja de Logística — un tipo de contenedor","Registro de Pedidos Pendientes — un registro de artículos retrasados"], correct:0, explanation:"BOL (Bill of Lading) is the most important shipping document. It serves as a receipt, title to goods, and contract. Always review before signing.", explanationEs:"BOL (Conocimiento de Embarque) es el documento de envío más importante. Sirve como recibo, título de bienes y contrato. Siempre revísalo antes de firmar." },
      { id:"lg-q2", type:"situation", skill:"cultural", question:"A shipment arrives with 20 fewer units than the purchase order. What must you do before the driver leaves?", questionEs:"Un envío llega con 20 unidades menos de lo que indica la orden de compra. ¿Qué debes hacer antes de que el conductor se vaya?", options:["Sign the BOL and report it later","Note the shortage on the BOL and have the driver sign the note","Call the supplier first","Refuse the entire shipment"], optionsEs:["Firmar el BOL y reportarlo después","Anotar la faltante en el BOL y hacer que el conductor firme la nota","Llamar al proveedor primero","Rechazar todo el envío"], correct:1, explanation:"Documenting a shortage before the driver leaves is critical. Once the driver leaves without a noted discrepancy, it becomes very difficult to file a claim.", explanationEs:"Documentar una faltante antes de que el conductor se vaya es crítico. Una vez que el conductor se va sin una discrepancia anotada, se vuelve muy difícil presentar un reclamo." },
      { id:"lg-q3", type:"multiple-choice", skill:"vocabulary", question:"What does 'OTD rate' mean in logistics performance reporting?", questionEs:"¿Qué significa 'OTD rate' en informes de desempeño de logística?", options:["On-Time Delivery rate","Over-The-Dock rate","Order-To-Door rate","Outbound Truck Density rate"], optionsEs:["Tasa de entrega a tiempo","Tasa sobre el muelle","Tasa de orden a puerta","Tasa de densidad de camiones de salida"], correct:0, explanation:"OTD = On-Time Delivery. It measures what percentage of shipments arrive by the promised date. A key KPI for all carriers and logistics providers.", explanationEs:"OTD = Entrega a Tiempo. Mide qué porcentaje de envíos llega en la fecha prometida. Un KPI clave para todos los transportistas y proveedores de logística." },
      { id:"lg-q4", type:"translate", skill:"comprehension", question:"A vendor says: 'We have a net-30 payment term.' What does this mean?", questionEs:"Un proveedor dice: 'We have a net-30 payment term.' ¿Qué significa esto?", options:["Payment is required immediately","Payment is due 30 days after the invoice date","You can negotiate the price down 30%","The order ships in 30 days"], optionsEs:["El pago se requiere de inmediato","El pago vence 30 días después de la fecha de la factura","Puedes negociar el precio a la baja un 30%","El pedido se envía en 30 días"], correct:1, explanation:"Net-30 = payment due 30 days from invoice date. Common terms include net-15, net-30, and net-60.", explanationEs:"Net-30 = pago vence 30 días desde la fecha de la factura. Los términos comunes incluyen net-15, net-30 y net-60." },
      { id:"lg-q5", type:"situation", skill:"cultural", question:"A carrier's OTD rate falls to 71% against a 95% SLA. What is the correct professional response?", questionEs:"La tasa OTD de un transportista cae al 71% contra un SLA del 95%. ¿Cuál es la respuesta profesional correcta?", options:["Immediately terminate the contract","Issue a formal corrective action notice and request a written improvement plan","Send a casual email asking them to do better","Accept the poor performance silently"], optionsEs:["Terminar el contrato de inmediato","Emitir un aviso formal de acción correctiva y solicitar un plan de mejora escrito","Enviar un correo casual pidiéndoles que mejoren","Aceptar el mal desempeño en silencio"], correct:1, explanation:"A formal CAR (Corrective Action Request) is the professional and contractually appropriate step when a carrier breaches SLA.", explanationEs:"Una CAR (Solicitud de Acción Correctiva) formal es el paso profesional y contractualmente apropiado cuando un transportista incumple el SLA." },
      { id:"lg-q6", type:"multiple-choice", skill:"vocabulary", question:"In a warehouse, what does 'FIFO' mean?", questionEs:"En un almacén, ¿qué significa 'FIFO'?", options:["Find It, File It, Organize It","First In, First Out — oldest inventory is used/shipped first","Fast Items, Fast Operations","Full Inventory, Full Output"], optionsEs:["Encuéntralo, archívalo, organízalo","Primero en entrar, primero en salir — el inventario más antiguo se usa/envía primero","Artículos rápidos, operaciones rápidas","Inventario completo, producción completa"], correct:1, explanation:"FIFO = First In, First Out. It ensures oldest inventory is used first, preventing expiration and spoilage. Critical for food, pharma, and perishables.", explanationEs:"FIFO = Primero en entrar, primero en salir. Asegura que el inventario más antiguo se use primero, previniendo vencimiento y deterioro. Crítico para alimentos, farmacéuticos y perecederos." },
      { id:"lg-q7", type:"translate", skill:"comprehension", question:"A procedure says: 'Any item not on the PO must be refused.' What must you do with a delivered item not on the purchase order?", questionEs:"Un procedimiento dice: 'Any item not on the PO must be refused.' ¿Qué debes hacer con un artículo entregado que no está en la orden de compra?", options:["Accept it and store it separately","Refuse delivery of that item","Accept it and notify purchasing later","Ask the driver what to do"], optionsEs:["Aceptarlo y almacenarlo por separado","Rechazar la entrega de ese artículo","Aceptarlo y notificar a compras después","Preguntarle al conductor qué hacer"], correct:1, explanation:"Never accept items not on the PO. Unauthorized items create inventory discrepancies and potential fraud exposure.", explanationEs:"Nunca aceptes artículos que no están en la OC. Los artículos no autorizados crean discrepancias de inventario y exposición potencial a fraude." },
      { id:"lg-q8", type:"multiple-choice", skill:"cultural", question:"In US logistics, what does it mean to 'file a claim' with a carrier?", questionEs:"En logística en EE.UU., ¿qué significa 'file a claim' con un transportista?", options:["Submit a complaint on social media","Formally request compensation for lost or damaged goods","Ask for a delivery update","Request a price discount on the next shipment"], optionsEs:["Publicar una queja en redes sociales","Solicitar formalmente compensación por bienes perdidos o dañados","Pedir una actualización de entrega","Solicitar un descuento en el próximo envío"], correct:1, explanation:"'File a claim' = submit a formal written request for financial compensation for loss or damage during transit. Must be documented with photos and signed BOL.", explanationEs:"'File a claim' = presentar una solicitud formal escrita de compensación financiera por pérdida o daño durante el tránsito. Debe documentarse con fotos y BOL firmado." },
    ],
  },

  // ─── EDUCATION ────────────────────────────────────────────────────────────
  {
    industry: "education",
    title: "Education English — Industry Quiz",
    titleEs: "Inglés para Educación — Quiz de Industria",
    description: "Test your education English: student interactions, parent communication, IEP language, and US school culture.",
    descriptionEs: "Pon a prueba tu inglés para educación: interacciones con estudiantes, comunicación con padres, lenguaje de IEP y cultura escolar en EE.UU.",
    passingScore: 70,
    questions: [
      { id:"ed-q1", type:"multiple-choice", skill:"vocabulary", question:"What does 'IEP' stand for in US special education?", questionEs:"¿Qué significa 'IEP' en la educación especial en EE.UU.?", options:["Individual Evaluation Protocol","Individualized Education Program","Integrated English Practice","Instructor Evaluation Plan"], optionsEs:["Protocolo de Evaluación Individual","Programa de Educación Individualizado","Práctica de Inglés Integrado","Plan de Evaluación del Instructor"], correct:1, explanation:"IEP = Individualized Education Program. A legally mandated document under IDEA that outlines accommodations, goals, and services for students with disabilities.", explanationEs:"IEP = Programa de Educación Individualizado. Un documento con mandato legal bajo IDEA que describe acomodaciones, metas y servicios para estudiantes con discapacidades." },
      { id:"ed-q2", type:"situation", skill:"cultural", question:"A parent calls upset about their child's grade. What is the professional response?", questionEs:"Un padre llama molesto sobre la calificación de su hijo. ¿Cuál es la respuesta profesional?", options:["Defend the grade immediately","Thank them for calling, listen fully, then explain the grade with specific evidence","Tell them to email the principal","Say the grade cannot be changed"], optionsEs:["Defender la calificación de inmediato","Agradecerles por llamar, escuchar completamente, luego explicar la calificación con evidencia específica","Decirles que le escriban al director","Decir que la calificación no puede cambiar"], correct:1, explanation:"US school culture values parent partnership. Always listen first, then explain with specific evidence. A defensive response escalates the situation.", explanationEs:"La cultura escolar de EE.UU. valora la asociación con los padres. Siempre escucha primero, luego explica con evidencia específica. Una respuesta defensiva escala la situación." },
      { id:"ed-q3", type:"translate", skill:"comprehension", question:"A colleague says: 'She's performing above benchmark for her grade level.' What does this mean?", questionEs:"Un colega dice: 'She's performing above benchmark for her grade level.' ¿Qué significa esto?", options:["She's struggling in class","She's performing better than the expected standard for her age/grade","She was promoted early","She needs additional testing"], optionsEs:["Está teniendo dificultades en clase","Está rindiendo mejor que el estándar esperado para su edad/grado","Fue promovida anticipadamente","Necesita pruebas adicionales"], correct:1, explanation:"'Benchmark' = the expected level of performance for a grade. 'Above benchmark' = performing better than the standard. 'Below benchmark' = needs additional support.", explanationEs:"'Benchmark' = el nivel esperado de desempeño para un grado. 'Above benchmark' = rindiendo mejor que el estándar. 'Below benchmark' = necesita apoyo adicional." },
      { id:"ed-q4", type:"multiple-choice", skill:"vocabulary", question:"In US education, what does 'differentiated instruction' mean?", questionEs:"En la educación de EE.UU., ¿qué significa 'differentiated instruction'?", options:["Teaching different subjects","Adapting teaching methods to meet different students' learning needs","Using only one teaching style","Separating students by ability into different classrooms"], optionsEs:["Enseñar diferentes materias","Adaptar los métodos de enseñanza para satisfacer las diferentes necesidades de aprendizaje de los estudiantes","Usar solo un estilo de enseñanza","Separar a los estudiantes por habilidad en diferentes salones"], correct:1, explanation:"Differentiated instruction means modifying content, process, and assessment based on individual student needs, readiness, and learning styles.", explanationEs:"La instrucción diferenciada significa modificar el contenido, el proceso y la evaluación basándose en las necesidades individuales, la preparación y los estilos de aprendizaje del estudiante." },
      { id:"ed-q5", type:"situation", skill:"grammar", question:"Which is the most professional way to redirect an off-task student?", questionEs:"¿Cuál es la forma más profesional de redirigir a un estudiante fuera de tarea?", options:["'Hey! Stop that right now!'","'Please put your phone away and open your textbook to page 45.'","'I can't believe you're doing that again.'","'What are you doing? This is class!'"], optionsEs:["'¡Hey! ¡Para eso ahora mismo!'","'Por favor guarda tu teléfono y abre tu libro de texto en la página 45.'","'No puedo creer que estés haciendo eso de nuevo.'","'¿Qué estás haciendo? ¡Esto es clase!'"], correct:1, explanation:"Calm, specific instructions work better than emotional reactions. Tell the student exactly what to do, not just what to stop.", explanationEs:"Las instrucciones calmadas y específicas funcionan mejor que las reacciones emocionales. Dile al estudiante exactamente qué hacer, no solo qué parar." },
      { id:"ed-q6", type:"multiple-choice", skill:"cultural", question:"In a US IEP meeting, parents are described as:", questionEs:"En una reunión de IEP en EE.UU., los padres se describen como:", options:["Observers with no voting rights","Consultants who are paid for their input","Equal members of the IEP team","Optional participants who may be excluded"], optionsEs:["Observadores sin derecho a voto","Consultores a quienes se les paga por su opinión","Miembros iguales del equipo de IEP","Participantes opcionales que pueden ser excluidos"], correct:2, explanation:"Under IDEA (Individuals with Disabilities Education Act), parents are legally equal partners on the IEP team with full rights to consent, disagree, and request changes.", explanationEs:"Bajo IDEA (Ley de Educación para Personas con Discapacidades), los padres son socios iguales legalmente en el equipo de IEP con plenos derechos a dar consentimiento, estar en desacuerdo y solicitar cambios." },
      { id:"ed-q7", type:"translate", skill:"vocabulary", question:"A teacher says: 'I need to submit grades by end of term.' What does 'end of term' mean?", questionEs:"Un maestro dice: 'I need to submit grades by end of term.' ¿Qué significa 'end of term'?", options:["End of the school day","End of the grading period (semester or quarter)","End of the teacher's employment","End of the school year"], optionsEs:["Fin del día escolar","Fin del período de calificaciones (semestre o trimestre)","Fin del empleo del maestro","Fin del año escolar"], correct:1, explanation:"'End of term' = the end of a grading period. A school year typically has 2 semesters or 4 quarters. Grades must be submitted to the registrar by then.", explanationEs:"'End of term' = el final de un período de calificaciones. Un año escolar típicamente tiene 2 semestres o 4 trimestres. Las calificaciones deben enviarse al registrador para entonces." },
      { id:"ed-q8", type:"multiple-choice", skill:"cultural", question:"In US schools, what does 'chronic absenteeism' mean?", questionEs:"En las escuelas de EE.UU., ¿qué significa 'chronic absenteeism'?", options:["Missing more than 3 days per year","Missing 10% or more of school days in a year","Being late more than 5 times","Missing a major test"], optionsEs:["Faltar más de 3 días por año","Faltar al 10% o más de los días escolares en un año","Llegar tarde más de 5 veces","Faltar a un examen importante"], correct:1, explanation:"Chronic absenteeism = missing 10% or more of school days (~18+ days in a 180-day year). It is a critical indicator of student risk and school performance.", explanationEs:"El ausentismo crónico = faltar al 10% o más de los días escolares (~18+ días en un año de 180 días). Es un indicador crítico de riesgo estudiantil y desempeño escolar." },
    ],
  },

  // ─── HOSPITALITY ──────────────────────────────────────────────────────────
  {
    industry: "hospitality",
    title: "Hospitality English — Industry Quiz",
    titleEs: "Inglés para Hotelería y Turismo — Quiz de Industria",
    description: "Test your hotel and tourism English: guest service, complaint resolution, revenue terms, and US hospitality culture.",
    descriptionEs: "Pon a prueba tu inglés para hotelería: servicio al huésped, resolución de quejas, términos de ingresos y cultura de hospitalidad en EE.UU.",
    passingScore: 70,
    questions: [
      { id:"hs-q1", type:"multiple-choice", skill:"vocabulary", question:"In hotel revenue management, what does 'RevPAR' stand for?", questionEs:"En la gestión de ingresos hoteleros, ¿qué significa 'RevPAR'?", options:["Revenue Per Available Room","Reservations Per Arrival Rate","Revenue from Parking and Restaurants","Room-Based Annual Revenue"], optionsEs:["Ingreso por habitación disponible","Reservas por tasa de llegada","Ingreso de estacionamiento y restaurantes","Ingreso anual basado en habitaciones"], correct:0, explanation:"RevPAR = Revenue Per Available Room. It combines occupancy rate and average daily rate (ADR) into one metric. The key hotel performance indicator.", explanationEs:"RevPAR = Ingreso Por Habitación Disponible. Combina la tasa de ocupación y la tarifa diaria promedio (ADR) en una métrica. El indicador clave de rendimiento hotelero." },
      { id:"hs-q2", type:"situation", skill:"cultural", question:"A guest is angry about a noisy room. What is the correct response model?", questionEs:"Un huésped está enojado por una habitación ruidosa. ¿Cuál es el modelo de respuesta correcto?", options:["Apologize and offer only an explanation","Use the LAST model: Listen, Apologize, Solve, Thank","Ask the guest to lower their voice first","Tell them the hotel is fully booked so nothing can be done"], optionsEs:["Disculparse y solo ofrecer una explicación","Usar el modelo LAST: Escuchar, Disculparse, Solucionar, Agradecer","Pedirle al huésped que baje la voz primero","Decirle que el hotel está lleno y no se puede hacer nada"], correct:1, explanation:"The LAST model (Listen, Apologize, Solve, Thank) is the gold standard for US hospitality complaint resolution. Never argue — always own the problem.", explanationEs:"El modelo LAST (Escuchar, Disculparse, Solucionar, Agradecer) es el estándar de oro para la resolución de quejas en la hostelería de EE.UU. Nunca argumentes — siempre asume el problema." },
      { id:"hs-q3", type:"translate", skill:"vocabulary", question:"The front desk offers to 'upgrade your room.' What does this mean?", questionEs:"La recepción ofrece 'upgrade your room.' ¿Qué significa esto?", options:["Clean the room again","Move you to a better or larger room, often at a discounted rate","Repair something in your current room","Change your room number"], optionsEs:["Limpiar la habitación de nuevo","Moverte a una habitación mejor o más grande, a menudo a tarifa con descuento","Reparar algo en tu habitación actual","Cambiar el número de tu habitación"], correct:1, explanation:"A room upgrade moves the guest to a higher category room. In US hotels, it's a common upselling tactic and guest benefit.", explanationEs:"Una mejora de habitación mueve al huésped a una habitación de categoría superior. En los hoteles de EE.UU., es una táctica común de venta adicional y beneficio para el huésped." },
      { id:"hs-q4", type:"multiple-choice", skill:"vocabulary", question:"What are 'amenities' in a hotel context?", questionEs:"¿Qué son las 'amenities' en un contexto hotelero?", options:["The hotel's legal agreements","Facilities and services provided to guests (pool, gym, breakfast, etc.)","The hotel staff's uniforms","A type of room service menu"], optionsEs:["Los acuerdos legales del hotel","Instalaciones y servicios proporcionados a los huéspedes (piscina, gimnasio, desayuno, etc.)","Los uniformes del personal del hotel","Un tipo de menú de servicio a la habitación"], correct:1, explanation:"Amenities = extra features and services included with the stay. Examples: pool, spa, gym, breakfast, parking, Wi-Fi. They affect a guest's perception of value.", explanationEs:"Amenities = características y servicios adicionales incluidos con la estadía. Ejemplos: piscina, spa, gimnasio, desayuno, estacionamiento, Wi-Fi. Afectan la percepción de valor del huésped." },
      { id:"hs-q5", type:"situation", skill:"grammar", question:"Which phrase correctly closes a guest check-in interaction?", questionEs:"¿Qué frase cierra correctamente una interacción de check-in con un huésped?", options:["Okay, bye.","Here's your key. See ya.","Here are your key cards. Your room is on the 4th floor. Enjoy your stay!","Your room number is 412. Go there now."], optionsEs:["Okay, adiós.","Aquí está tu llave. Hasta luego.","Aquí están sus tarjetas llave. Su habitación está en el 4to piso. ¡Disfrute su estadía!","Su número de habitación es 412. Vaya allá ahora."], correct:2, explanation:"'Enjoy your stay!' is the standard professional closing in US hospitality. Always hand over key cards warmly and give clear directions to the room.", explanationEs:"'Enjoy your stay!' es el cierre profesional estándar en la hostelería de EE.UU. Siempre entrega las tarjetas llave con calidez y da direcciones claras a la habitación." },
      { id:"hs-q6", type:"multiple-choice", skill:"cultural", question:"In US hotel culture, what does 'OTA' stand for and why does it matter?", questionEs:"En la cultura hotelera de EE.UU., ¿qué significa 'OTA' y por qué importa?", options:["On-Time Arrival — for tracking early guests","Online Travel Agency (Expedia, Booking.com) — channels where hotels pay a commission","Occupancy Tax Assessment — a government fee","Overnight Transfer Authorization — for room changes"], optionsEs:["Llegada a tiempo — para rastrear huéspedes tempranos","Agencia de Viajes en Línea (Expedia, Booking.com) — canales donde los hoteles pagan comisión","Evaluación de Impuesto de Ocupación — una tarifa gubernamental","Autorización de Transferencia Nocturna — para cambios de habitación"], correct:1, explanation:"OTA = Online Travel Agency. Hotels pay 15–25% commissions to OTAs. Revenue managers try to shift bookings to the hotel's direct website to reduce commission costs.", explanationEs:"OTA = Agencia de Viajes en Línea. Los hoteles pagan comisiones del 15–25% a las OTAs. Los gerentes de ingresos intentan cambiar reservas al sitio web directo del hotel para reducir costos de comisión." },
      { id:"hs-q7", type:"translate", skill:"comprehension", question:"A policy says: 'Respond to negative reviews within 24 hours without arguing with the reviewer.' What must you do?", questionEs:"Una política dice: 'Respond to negative reviews within 24 hours without arguing.' ¿Qué debes hacer?", options:["Ignore bad reviews","Post a response within 24 hours acknowledging the guest's experience professionally","Ask the guest to delete the review","Defend the hotel's position publicly"], optionsEs:["Ignorar las malas reseñas","Publicar una respuesta en 24 horas reconociendo la experiencia del huésped profesionalmente","Pedirle al huésped que elimine la reseña","Defender públicamente la posición del hotel"], correct:1, explanation:"US hospitality standard: respond fast, acknowledge the experience empathetically, and offer a specific remedy. Never argue online — it looks worse than the original complaint.", explanationEs:"Estándar de hostelería en EE.UU.: responde rápido, reconoce la experiencia con empatía y ofrece un remedio específico. Nunca argumentes en línea — se ve peor que la queja original." },
      { id:"hs-q8", type:"multiple-choice", skill:"vocabulary", question:"What is 'ADR' in hotel performance metrics?", questionEs:"¿Qué es el 'ADR' en las métricas de desempeño hotelero?", options:["Annual Discount Rate","Average Daily Rate — the average revenue per occupied room per night","Amenity Delivery Report","Authorized Discount Request"], optionsEs:["Tasa de Descuento Anual","Tarifa Diaria Promedio — el ingreso promedio por habitación ocupada por noche","Informe de Entrega de Servicios","Solicitud de Descuento Autorizado"], correct:1, explanation:"ADR = Average Daily Rate. It measures the average revenue earned per occupied room. Together with occupancy, it determines RevPAR.", explanationEs:"ADR = Tarifa Diaria Promedio. Mide el ingreso promedio ganado por habitación ocupada. Junto con la ocupación, determina el RevPAR." },
    ],
  },

  // ─── MANUFACTURING ────────────────────────────────────────────────────────
  {
    industry: "manufacturing",
    title: "Manufacturing English — Industry Quiz",
    titleEs: "Inglés para Manufactura — Quiz de Industria",
    description: "Test your manufacturing English: safety protocols, quality terms, lean vocabulary, and US plant culture.",
    descriptionEs: "Pon a prueba tu inglés para manufactura: protocolos de seguridad, términos de calidad, vocabulario lean y cultura de planta en EE.UU.",
    passingScore: 70,
    questions: [
      { id:"mf-q1", type:"multiple-choice", skill:"vocabulary", question:"What does 'LOTO' or 'lockout/tagout' mean on a US manufacturing floor?", questionEs:"¿Qué significa 'LOTO' o 'lockout/tagout' en una planta de manufactura en EE.UU.?", options:["A type of lottery for safety prizes","A procedure to isolate equipment from energy sources before maintenance","A quality inspection process","A shift scheduling method"], optionsEs:["Un tipo de lotería para premios de seguridad","Un procedimiento para aislar equipos de fuentes de energía antes del mantenimiento","Un proceso de inspección de calidad","Un método de programación de turnos"], correct:1, explanation:"LOTO (Lockout/Tagout) is a federally required safety procedure under OSHA. It ensures machines are properly shut off before anyone performs maintenance or repair.", explanationEs:"LOTO (Bloqueo/Etiquetado) es un procedimiento de seguridad requerido federalmente bajo OSHA. Asegura que las máquinas estén correctamente apagadas antes de que alguien realice mantenimiento o reparación." },
      { id:"mf-q2", type:"situation", skill:"cultural", question:"You spot a surface defect on 15% of the parts you're producing. What should you do?", questionEs:"Detectas un defecto superficial en el 15% de las piezas que produces. ¿Qué debes hacer?", options:["Continue producing and mention it at the end of shift","Immediately flag the issue to your supervisor and stop affected production","Fix the defects yourself before anyone sees","Wait to see if the defect worsens"], optionsEs:["Continuar produciendo y mencionarlo al final del turno","Señalar el problema de inmediato a tu supervisor y detener la producción afectada","Corregir los defectos tú mismo antes de que alguien lo vea","Esperar a ver si el defecto empeora"], correct:1, explanation:"In US manufacturing, speaking up immediately about quality issues is valued and expected. Catching defects early prevents downstream waste. 'Good catch' is high praise.", explanationEs:"En la manufactura de EE.UU., señalar problemas de calidad de inmediato es valorado y esperado. Detectar defectos temprano previene desperdicios posteriores. 'Good catch' es un gran elogio." },
      { id:"mf-q3", type:"multiple-choice", skill:"vocabulary", question:"What does 'OEE' measure in manufacturing?", questionEs:"¿Qué mide el 'OEE' en manufactura?", options:["Overall Employee Efficiency","Overall Equipment Effectiveness — a combined measure of availability, performance, and quality","Outbound Equipment Exports","Operator Error Evaluation"], optionsEs:["Eficiencia general del empleado","Efectividad General del Equipo — una medida combinada de disponibilidad, rendimiento y calidad","Exportaciones de equipos de salida","Evaluación de errores del operador"], correct:1, explanation:"OEE = Overall Equipment Effectiveness. It combines Availability × Performance × Quality. World-class OEE is ~85%. It is the key lean manufacturing metric.", explanationEs:"OEE = Efectividad General del Equipo. Combina Disponibilidad × Rendimiento × Calidad. El OEE de clase mundial es ~85%. Es la métrica clave de manufactura esbelta." },
      { id:"mf-q4", type:"translate", skill:"comprehension", question:"The production report says: 'First-pass yield is 94% against a 99% target.' What does this mean?", questionEs:"El informe de producción dice: 'El rendimiento de primer paso es 94% contra un objetivo del 99%.' ¿Qué significa esto?", options:["94% of workers passed their first safety test","94% of parts pass quality inspection without rework on the first attempt","94% of production targets were met","94% of machines are running correctly"], optionsEs:["El 94% de los trabajadores aprobaron su primera prueba de seguridad","El 94% de las piezas pasan la inspección de calidad sin retrabajo en el primer intento","Se cumplieron el 94% de los objetivos de producción","El 94% de las máquinas están funcionando correctamente"], correct:1, explanation:"First-pass yield (FPY) = the percentage of units that pass quality inspection on the first attempt, without rework. Higher is better — 99% means only 1% defect rate.", explanationEs:"Rendimiento de primer paso (FPY) = el porcentaje de unidades que pasan la inspección de calidad en el primer intento, sin retrabajo. Más alto es mejor — 99% significa solo 1% de tasa de defectos." },
      { id:"mf-q5", type:"multiple-choice", skill:"vocabulary", question:"In lean manufacturing, what is a 'Kaizen event'?", questionEs:"En manufactura esbelta, ¿qué es un 'Kaizen event'?", options:["A company celebration for hitting production targets","A focused, short-term improvement project (usually 3–5 days) to solve a specific problem","A type of equipment inspection","A new employee onboarding session"], optionsEs:["Una celebración de empresa por alcanzar objetivos de producción","Un proyecto de mejora enfocado y de corto plazo (generalmente 3–5 días) para resolver un problema específico","Un tipo de inspección de equipo","Una sesión de incorporación de nuevos empleados"], correct:1, explanation:"Kaizen = continuous improvement in Japanese. A Kaizen event is an intensive, team-based workshop focused on rapidly improving a specific process or work area.", explanationEs:"Kaizen = mejora continua en japonés. Un evento Kaizen es un taller intensivo y basado en equipo enfocado en mejorar rápidamente un proceso o área de trabajo específica." },
      { id:"mf-q6", type:"situation", skill:"cultural", question:"A machine starts making an unusual grinding noise. What is the correct action?", questionEs:"Una máquina empieza a hacer un ruido de raspado inusual. ¿Cuál es la acción correcta?", options:["Continue operating and report at end of shift","Stop the machine, apply LOTO, and immediately notify the supervisor","Try to fix the noise yourself","Turn up the volume on the radio so it's less noticeable"], optionsEs:["Continuar operando y reportar al final del turno","Detener la máquina, aplicar LOTO y notificar inmediatamente al supervisor","Intentar arreglar el ruido tú mismo","Subir el volumen de la radio para que sea menos notable"], correct:1, explanation:"Unusual noises indicate potential mechanical failure. US manufacturing safety protocols require stopping the equipment, applying LOTO, and reporting immediately — not waiting.", explanationEs:"Los ruidos inusuales indican una posible falla mecánica. Los protocolos de seguridad de manufactura en EE.UU. requieren detener el equipo, aplicar LOTO y reportar de inmediato — no esperar." },
      { id:"mf-q7", type:"translate", skill:"vocabulary", question:"A supervisor says: 'We need to reduce our cycle time on this line.' What is 'cycle time'?", questionEs:"Un supervisor dice: 'We need to reduce our cycle time on this line.' ¿Qué es el 'cycle time'?", options:["The time between employee breaks","The time it takes to complete one unit from start to finish","The time the machine is not in use","The number of work cycles per month"], optionsEs:["El tiempo entre los descansos de los empleados","El tiempo que tarda en completarse una unidad de principio a fin","El tiempo que la máquina no está en uso","El número de ciclos de trabajo por mes"], correct:1, explanation:"Cycle time = the time required to complete one production cycle for a single unit. Reducing cycle time = producing more units in the same time.", explanationEs:"Tiempo de ciclo = el tiempo requerido para completar un ciclo de producción para una sola unidad. Reducir el tiempo de ciclo = producir más unidades en el mismo tiempo." },
      { id:"mf-q8", type:"multiple-choice", skill:"cultural", question:"In US manufacturing, who is responsible for quality?", questionEs:"En la manufactura de EE.UU., ¿quién es responsable de la calidad?", options:["Only the Quality Control department","Only the plant manager","Everyone on the production floor — quality is a shared responsibility","Only the final inspector"], optionsEs:["Solo el departamento de Control de Calidad","Solo el gerente de la planta","Todos en el piso de producción — la calidad es una responsabilidad compartida","Solo el inspector final"], correct:2, explanation:"In US manufacturing culture, quality is everyone's responsibility. Every operator is trained to identify and flag defects. Waiting for the QC inspector is not acceptable.", explanationEs:"En la cultura de manufactura de EE.UU., la calidad es responsabilidad de todos. Cada operador está entrenado para identificar y señalar defectos. Esperar al inspector de QC no es aceptable." },
    ],
  },
];
